/* The scripted card pool. Every name must exist in AlgomancyCards-OracleText.json.
 * Grown by scripts/gen-card.mjs (the M3 burn-down pipeline): it appends names
 * here, re-runs extract-printed.mjs, and emits DSL/test skeletons.
 * Keep one name per line — gen-card.mjs inserts before the closing bracket. */
export const POOL = [
  // prototype 15
  'Ignis Sprite',
  'Rune Channeler',
  'Mischievous Reclaimer',
  'Ephemeral Skywalker',
  'Smouldering Inferno',
  'Luminous Arc',
  'Flame of History',
  'All-Consuming Blaze',
  'Flame Juggle',
  'Lonely Forager',
  'Jelly',
  'Curio Drifter',
  'Leaping Lillik',
  'Dreadwave Devourer',
  'Good Whale',
  // graft & rulings additions
  'Oracle of the Flame',
  'Accelerated Germination',
  'Astral Tidewraith',
  'Bellowing Boulder',
  'Dune Drifter',
  'Arc Lightning',
  // mechanics batch 2 (stat layer 4, Deadly, Sneaky, haste step, token makers, Ambush)
  'Rampart Guardian',
  'Child of Aether',
  'Tidepool Terror',
  'Orblish Horroth',
  'Whispering Mantid',
  'Molten Upheaval',
  'Awoken Tomb',
  'Aberrant Populace',
  'Spectrogenesis',
  'Recyclable Sentinel',
  // tokens
  'Fireball',
  'Wisp',
  'Robot',
  'Chitin Shredder',
  'Crumbling Ancient',
  'Slink',
  'Resonant Form',
  'Noxious Sporefiend',
  'Biotoxicity',
  'Geode',
  'Accumulated Nucleation',
  'Poison',
  'Crystal',
  'Ambling Mountaintop',
  'Bloated Manablub',
  'Boreal Wanderer',
  'A Pile of Rubbish',
  'Astralith',
  'Construct Overseer',
  'Channeled Amalgam',
  'Arcane Concentrator',
  'Adversary of the Deep',
  'Bumblecrab',
  'Carapace Devourer',
  'Channeled Boon',
  'Burning Vengeance',
  'Guardian of the Grotto',
  'Engorged Caudex',
  'Forager of the Fallen',
  'Bloomcaster',
  'Flourishing Flora',
  'Flamebreath Initiate',
  'Embermaw Fledgling',
  'A Fast Pile of Rocks',
  'Aetherflux Golem',
  'Battle',
  'Bubb',
  'Crevice Lurker',
  'Deathglow Strider',
  'Earth Resource',
  'Eminence of the Barrens',
  'Enigmatic Warder',
  'Fight',
  'Flowstone Arcanite',
  'Graxxlid',
  'Haboob',
  'Hooba-Lan',
  'Lithoghul',
  'Lost Guardian',
  'Malformed Monstrosity',
  'Metamorphic Luminary',
  'Meteor Shower',
  'Mirage Scuttler',
  'Mohruung',
  'Morphic Mentor',
  'Nectar Ridge Oracle',
  'Oorblak',
  'Perpetual Construct',
  'Plodding Pebble',
  'Reality Bender',
  'Restitution',
  'Return to Nature',
  'Roving Quillback',
  'Ruinbringer',
  'Sandstone Defender',
  'Seismomancy',
  'Skybreaker',
  'Squish',
  'Stoneborn Progenitor',
  'Swirling Shardform',
  'Tenebrous Bulborb',
  'The Bonesculptor',
  'Throw off a Cliff',
  'Throwing Boulder',
  'Towering Colossus',
  'Tranquility',
  'A Pile of Runes',
  'Mirrorback Ambusher',
  'Origon',
  'Stasis Sentry',
  'Unfinished Creation',
  'Abyssal Evocation',
  'Animated Spark',
  'Bloodwind Revenant',
  'Cinder Scuttler',
  'Conduit of Pain',
  'Delver of Mysteries',
  'Emberflame Enlightener',
  'Envoy of Lightning',
  'Fire Resource',
  'Flame Shield',
  'General Smof',
  'Ghord',
  'Gravitational Correction',
  'Harbinger of Immolation',
  'Hooba-Lin',
  'Immolate',
  'Infernal Cultivator',
  'Infernal Wispweaver',
  'Molten Riftbreaker',
  'Nimbus Eel',
  'Ravenous Fireslinger',
  'Reclaimer of Secrets',
  'Resurrect',
  'Rousing Spirit',
  'Sacrificial Burst',
  'Soul Swallower',
  'Soul Tithe',
  'Sparkwraith',
  'Spirit of Vengeance',
  'Spiteful Shadow',
  'Static Courier',
  'Stormsowing Nimbus',
  'Twin Flame',
  'Unstable Apparition',
  'Voltwrath Behemoth',
  'Wildfire',
  'Amphivore',
  'Bripp',
  'Celestial Purge',
  'Cosmic Reversal',
  'Dreadspawn Horror',
  'Dreamfloat Drifter',
  'Echo of Despair',
  'Eldritch Reclaimer',
  'Frosted Denial',
  'Galerider Eel',
  'Hooba-Pon',
  'Insidious Invitation',
  'Lurking Slimebeast',
  'Minor Kraken',
  'Mirage Walker',
  'Null Drone',
  'Oracle of Foretelling',
  'Overwhelm',
  'Premonition',
  'Protective Adaptations',
  'Pull Under',
  'Recall',
  'Rider of the Tides',
  'Rippleback Skulker',
  'Seabed Shellcaster',
  'Shoreline Specter',
  'Soul Siphon',
  'Spawntender',
  'Spell Excavation',
  'Surly Stalker',
  'Tempest Wrangler',
  'Tidal Menace',
  'Tidal Reversion',
  'Tidelurker',
  'Tiderunner Initiate',
  'Tides of the Cosmos',
  'Upheaval',
  'Vaporweave Eidolon',
  'Water Resource',
  'Xenopod Progenitor',
  'Astral Painseeker',
  'Death Greeter',
  'Channel Through',
  'Molten Tormentor',
  'Slag Spewer',
  'Structural Collapse',
  'Unstable Form',
  'Demon of the Depths',
  'Tempest Oracle',
  'Torrential Reclamation',
  'Abduct',
  'Floral Singularity',
  'Ominous Growth',
  'The World Shepherd',
  'Wither and Bloom',
  'Aberrant Statweaver',
  'Ancient One',
  'Arcane Echo',
  'Automaton of Abundance',
  'Biomass Devourer',
  'Body Swap',
  'Borrower of Forms',
  'Celestial Fluxmorph',
  'Celestial Shifter',
  'Containment Protocol',
  'Cosmic Conspirator',
  'Deformant',
  'Discharge',
  'Dispatch Courier',
  'Download',
  'Eldritch Dreamtender',
  'Evolutionary Experiment',
  'Flux Constructor',
  'Flux Resonator',
  'Foretell',
  'Formless',
  'Hooba-Bot',
  'Instrument of Reassignment',
  'Interdiction Rift',
  'Invasive Reassignment',
  'Linked Extinction',
  'Living Forge',
  'Manufacture',
  'Monke',
  'Nebula Drifter',
  'Omniwield Evoker',
  'Perish',
  'Powerforge Synergist',
  'Reforge the Dead',
  'Refuse Reclaimer',
  'Riftwalker',
  'Scavenging Sentry',
  'Scrap For Parts',
  'Self-Assembly',
  'Soul Reaver',
  'Suppression Field',
  'Synaptic Energizer',
  'Technological Superiority',
  'Transmogrifant',
  'Trashling',
  'Unmake',
  'Unstable Refactor',
  'Unstable Singularity',
  'Void Memory',
  'Worldbender',
  'Aether Channeler',
  'Corroded Alchemy',
  'Decay Distributor',
  'Earthbound Replicator',
  'Spirit of Nature',
  'Aethercap Siphoner',
  'Galactic Germination',
  'Invasive Species',
  'Lumengrove Lurker',
  'Mindwarp Sporefrog',
  'All-Consuming Blight',
  'Bioremediation',
  'Boon of Protection',
  'Burgeon',
  'Corrupting Blight',
  'Earnest Defender',
  'Fungal Gardener',
  'Glowhaven Elder',
  'Growing Plague',
  'Hexbane Shiitake',
  'Hooba-Nan',
  'Hush Mush',
  'Inspiration',
  'Invigorate',
  'Jollyglop',
  'Luminary Leader',
  'Megadeath',
  'Might of the Grove',
  'Mindspore Fiend',
  'Mycelial Mentor',
  'Noxious Deathcap',
  'Noxious Demise',
  'Organic Exchange',
  'Overbloom',
  'Pack Leader',
  'Pathogenic Enclave',
  'Pernicious Photosynthesis',
  'Pestilent Mycelion',
  'Phytochemical Protection',
  'Plague Bellower',
  'Prickly Protector',
  'Ralph',
  'Rebalance',
  'Saprophytic Oracle',
  'Spawning Ground',
  'Spewing Mushroom',
  'Sporebloom Siren',
  'Sprouter',
  'Stellarspore Harvester',
  'Sudden Bloom',
  'Sylvan Sprouting',
  'Verdant Necrophage',
  'Verdant Vengeance',
  'Wandering Blightshell',
  'Warbloom Herald',
  'Woodland Warding',
  'Auric Ascendant',
  'Dematerialize',
  'Temporal Rift',
  'Transmutide Enigma',
  'Colossal Construction',
  'Reconfigure',
  'Rook',
  'Scrapyard Custodian',
  'The Silent',
  'Ember of Life',
  'Hearthwood Ancient',
  'Infernal Grovekeeper',
  'Rotspore Herald',
  'Volatile Toxicity',
  'Maelstrom Charger',
  'Malevolent Machinations',
  'Malicious Hardware',
  'Maw of Damnation',
  'Soulforger',

  // ── Light & Dark expansion ──
  'Abyssal Extortionist',
  'Afflicting Anima',
  'Air Plant',
  'Angel of Anguish',
  'Apex Prime',
  'Arbiter of Armistice',
  'Arbiter of Vitality',
  'Aurozoa',
  'Banishment',
  'Big Glimpse Card',
  'Blessed Thing',
  'Blight\'s End',
  'Blightmound',
  'Blightsea Polyp',
  'Blightwalker',
  'Blob of the Dark Order',
  'Bloppert',
  'Blurf',
  'Brough',
  'Buffer Overflow',
  'Burden of Life',
  'Burn the Blight',
  'Cadaverous Cultivator',
  'Calming Force',
  'Capture',
  'Cerebrox',
  'Chombot',
  'Collect Remains',
  'Colony of the Interworld',
  'Combustible Bogwalker',
  'Cosmic Devourer',
  'Counter Theif',
  'Covenant of the Damned',
  'Cthyrian Culler',
  'Cthyrian Rector',
  'Cull',
  'Darkblast',
  'Deathcoil Construct',
  'Debt Blep',
  'Debt Plant',
  'Deferral Drone',
  'Delver of the Ephemeral',
  'Divine Foresight',
  'Divine Intervention',
  'Dragnol',
  'Dream Lapse',
  'Dropslime',
  'Entropic Entity',
  'Equilibriate',
  'Exhume',
  'Feed to Hooba',
  'Fester',
  'Finality',
  'Flesh Tithe',
  'Flzzz',
  'Gatekeeper of Souls',
  'Glararr',
  'Glook',
  'Glutton of Absolution',
  'Godray',
  'Greed Angel',
  'Gridxlan',
  'Grim Bargain',
  'Grob',
  'Grox',
  'Hammer of Justice',
  'Hand Peeper',
  'Haunting Memories',
  'Hooba-God',
  'Hooba-Mon',
  'Hyper Beam',
  'Inexorable Miasma',
  'Insatiable Want',
  'Its Dark Bubb',
  'Iyngstra',
  'Just a Unit',
  'Keeper of Tithes',
  'Leave None Pure',
  'Legion of the Depths',
  'Life Channel',
  'Life Leech',
  'Life Plant',
  'Gublin',
  'Gzxyclop',
  'Life Power Dude',
  'Lifebound Seer',
  'Lilbot',
  'Living Vault',
  'Lurking Dread',
  'Maw of Despair',
  'Mindburn',
  'Muck Rummager',
  'Murkdrop Distiller',
  'Murkstalker',
  'Möbius\'s Corruption',
  'Necromantic Rebuke',
  'Necromorph',
  'No Hand Killer',
  'Nothyr',
  'Nullbringer',
  'Pale Tormentor',
  'Palewing',
  'Pallid Gorger',
  'Penance',
  'Pestilent Titan',
  'Plague Ritual',
  'Ploosh',
  'Prediction Prophet',
  'Primordial Coalescence',
  'Prismatic Observer',
  'Proliferating Slime',
  'Proph',
  'Prophecy Bug',
  'Reality Siphoner',
  'Reap the Due',
  'Reclaim the Fallen',
  'Retribution Thing',
  'Riftspawn Remnant',
  'Rime Wraith',
  'Rotbeast',
  'Rotling',
  'Rotwall',
  'Sacrifice Dude',
  'Sarcophage',
  'Scholar of the Void',
  'Scuttling Abomination',
  'Seer of Empty Spaces',
  'Shard Sprite',
  'Shib',
  'Siphon Life',
  'Skittering Blight',
  'Slurpr',
  'Spellbind',
  'Splort',
  'Spore of Regenesis',
  'Stalwart Sentinel',
  'Stellar Fission',
  'Suspend',
  'Swarmling',
  'The Everywhere',
  'The Foretold',
  'The Mighty Doot',
  'The Omniphage',
  'Thought Extraction',
  'Thoughtripper',
  'Tilling the Graves',
  'Tithe Enforcer',
  'Trench Stalker',
  'Triskaidekaphage',
  'Uglk',
  'Umbral Decay',
  'Unrelenting Horror',
  'Vengeance',
  'Visage of Ruin',
  'Visionary Construct',
  'Void Mandible',
  'Vroot',
  'Wake the Dead',
  'Waxen Witness',
  'Witness of the Crossing',
  'Writhing Host',
  'Xzydris',
  'Zephyrzoa',
  // R71: the Wraith token. It has a printed card and an oracle entry, so its
  // stats/type/text/art come from the pool like any other token (Wisp,
  // Fireball, Poison) — registry.ts carries behaviour only. It is a "Token
  // Unit" type, so DECK_LIST and the draft pools filter it out.
  'Wraith',
];
