/* The scripted card pool. Every name must exist in AlgomancyCards-OracleText.json.
 * Grown by scripts/gen-card.mjs (the M3 burn-down pipeline): it appends names
 * here, re-runs extract-printed.mjs, and emits DSL/test skeletons.
 * Keep one name per line — gen-card.mjs inserts before the closing bracket. */
export const POOL = [
  // prototype 15
  'Ignis Sprite',
  'Rune Channeler',
  'Mischievous Reclaimer',
  'Ephemeral Skywalker',
  'Smouldering Inferno',
  'Luminous Arc',
  'Flame of History',
  'All-Consuming Blaze',
  'Flame Juggle',
  'Lonely Forager',
  'Jelly',
  'Curio Drifter',
  'Leaping Lillik',
  'Dreadwave Devourer',
  'Good Whale',
  // graft & rulings additions
  'Oracle of the Flame',
  'Accelerated Germination',
  'Astral Tidewraith',
  'Bellowing Boulder',
  'Dune Drifter',
  'Arc Lightning',
  // mechanics batch 2 (stat layer 4, Deadly, Sneaky, haste step, token makers, Ambush)
  'Rampart Guardian',
  'Child of Aether',
  'Tidepool Terror',
  'Orblish Horroth',
  'Whispering Mantid',
  'Molten Upheaval',
  'Awoken Tomb',
  'Aberrant Populace',
  'Spectrogenesis',
  'Recyclable Sentinel',
  // tokens
  'Fireball',
  'Wisp',
  'Robot',
  'Chitin Shredder',
  'Crumbling Ancient',
  'Slink',
  'Resonant Form',
  'Noxious Sporefiend',
  'Biotoxicity',
  'Geode',
  'Accumulated Nucleation',
  'Poison',
  'Crystal',
  'Ambling Mountaintop',
  'Bloated Manablub',
  'Boreal Wanderer',
  'A Pile of Rubbish',
  'Astralith',
  'Construct Overseer',
  'Channeled Amalgam',
  'Arcane Concentrator',
  'Adversary of the Deep',
  'Bumblecrab',
  'Carapace Devourer',
  'Channeled Boon',
  'Burning Vengeance',
  'Guardian of the Grotto',
  'Engorged Caudex',
  'Forager of the Fallen',
  'Bloomcaster',
  'Flourishing Flora',
  'Flamebreath Initiate',
  'Embermaw Fledgling',
  'A Fast Pile of Rocks',
  'Aetherflux Golem',
  'Battle',
  'Bubb',
  'Crevice Lurker',
  'Deathglow Strider',
  'Earth Resource',
  'Eminence of the Barrens',
  'Enigmatic Warder',
  'Fight',
  'Flowstone Arcanite',
  'Graxxlid',
  'Haboob',
  'Hooba-Lan',
  'Lithoghul',
  'Lost Guardian',
  'Malformed Monstrosity',
  'Metamorphic Luminary',
  'Meteor Shower',
  'Mirage Scuttler',
  'Mohruung',
  'Morphic Mentor',
  'Nectar Ridge Oracle',
  'Oorblak',
  'Perpetual Construct',
  'Plodding Pebble',
  'Reality Bender',
  'Restitution',
  'Return to Nature',
  'Roving Quillback',
  'Ruinbringer',
  'Sandstone Defender',
  'Seismomancy',
  'Skybreaker',
  'Squish',
  'Stoneborn Progenitor',
  'Swirling Shardform',
  'Tenebrous Bulborb',
  'The Bonesculptor',
  'Throw off a Cliff',
  'Throwing Boulder',
  'Towering Colossus',
  'Tranquility',
  'A Pile of Runes',
  'Mirrorback Ambusher',
  'Origon',
  'Stasis Sentry',
  'Unfinished Creation',
  'Abyssal Evocation',
  'Animated Spark',
  'Bloodwind Revenant',
  'Cinder Scuttler',
  'Conduit of Pain',
  'Delver of Mysteries',
  'Emberflame Enlightener',
  'Envoy of Lightning',
  'Fire Resource',
  'Flame Shield',
  'General Smof',
  'Ghord',
  'Gravitational Correction',
  'Harbinger of Immolation',
  'Hooba-Lin',
  'Immolate',
  'Infernal Cultivator',
  'Infernal Wispweaver',
  'Molten Riftbreaker',
  'Nimbus Eel',
  'Ravenous Fireslinger',
  'Reclaimer of Secrets',
  'Resurrect',
  'Rousing Spirit',
  'Sacrificial Burst',
  'Soul Swallower',
  'Soul Tithe',
  'Sparkwraith',
  'Spirit of Vengeance',
  'Spiteful Shadow',
  'Static Courier',
  'Stormsowing Nimbus',
  'Twin Flame',
  'Unstable Apparition',
  'Voltwrath Behemoth',
  'Wildfire',
  'Amphivore',
  'Bripp',
  'Celestial Purge',
  'Cosmic Reversal',
  'Dreadspawn Horror',
  'Dreamfloat Drifter',
  'Echo of Despair',
  'Eldritch Reclaimer',
  'Frosted Denial',
  'Galerider Eel',
  'Hooba-Pon',
  'Insidious Invitation',
  'Lurking Slimebeast',
  'Minor Kraken',
  'Mirage Walker',
  'Null Drone',
  'Oracle of Foretelling',
  'Overwhelm',
  'Premonition',
  'Protective Adaptations',
  'Pull Under',
  'Recall',
  'Rider of the Tides',
  'Rippleback Skulker',
  'Seabed Shellcaster',
  'Shoreline Specter',
  'Soul Siphon',
  'Spawntender',
  'Spell Excavation',
  'Surly Stalker',
  'Tempest Wrangler',
  'Tidal Menace',
  'Tidal Reversion',
  'Tidelurker',
  'Tiderunner Initiate',
  'Tides of the Cosmos',
  'Upheaval',
  'Vaporweave Eidolon',
  'Water Resource',
  'Xenopod Progenitor',
  'Astral Painseeker',
  'Death Greeter',
  'Channel Through',
  'Molten Tormentor',
  'Slag Spewer',
  'Structural Collapse',
  'Unstable Form',
  'Demon of the Depths',
  'Tempest Oracle',
  'Torrential Reclamation',
];
