/* The scripted card pool. Every name must exist in AlgomancyCards-OracleText.json.
 * Grown by scripts/gen-card.mjs (the M3 burn-down pipeline): it appends names
 * here, re-runs extract-printed.mjs, and emits DSL/test skeletons.
 * Keep one name per line — gen-card.mjs inserts before the closing bracket. */
export const POOL = [
  // prototype 15
  'Ignis Sprite',
  'Rune Channeler',
  'Mischievous Reclaimer',
  'Ephemeral Skywalker',
  'Smouldering Inferno',
  'Luminous Arc',
  'Flame of History',
  'All-Consuming Blaze',
  'Flame Juggle',
  'Lonely Forager',
  'Jelly',
  'Curio Drifter',
  'Leaping Lillik',
  'Dreadwave Devourer',
  'Good Whale',
  // graft & rulings additions
  'Oracle of the Flame',
  'Accelerated Germination',
  'Astral Tidewraith',
  'Bellowing Boulder',
  'Dune Drifter',
  'Arc Lightning',
  // mechanics batch 2 (stat layer 4, Deadly, Sneaky, haste step, token makers, Ambush)
  'Rampart Guardian',
  'Child of Aether',
  'Tidepool Terror',
  'Orblish Horroth',
  'Whispering Mantid',
  'Molten Upheaval',
  'Awoken Tomb',
  'Aberrant Populace',
  'Spectrogenesis',
  'Recyclable Sentinel',
  // tokens
  'Fireball',
  'Wisp',
  'Robot',
  'Chitin Shredder',
  'Crumbling Ancient',
  'Slink',
  'Resonant Form',
  'Noxious Sporefiend',
  'Biotoxicity',
  'Geode',
  'Accumulated Nucleation',
  'Poison',
  'Crystal',
  'Ambling Mountaintop',
  'Bloated Manablub',
  'Boreal Wanderer',
  'A Pile of Rubbish',
  'Astralith',
  'Construct Overseer',
  'Channeled Amalgam',
  'Arcane Concentrator',
  'Adversary of the Deep',
  'Bumblecrab',
  'Carapace Devourer',
  'Channeled Boon',
  'Burning Vengeance',
  'Guardian of the Grotto',
  'Engorged Caudex',
  'Forager of the Fallen',
  'Bloomcaster',
  'Flourishing Flora',
  'Flamebreath Initiate',
  'Embermaw Fledgling',
];
