"""Every filesystem path this project uses, named once.

WHY THIS FILE EXISTS
--------------------
Ten modules used to open with `ROOT = Path(__file__).resolve().parent` and hang
their data directories off it. That works exactly as long as nothing moves. The
moment a file changes depth the constant silently repoints one level wrong —
no ImportError, no failing test, nothing red. You find out when the bot boots
and reports zero cards loaded.

So the paths live here instead. Moving `data/cards/` used to mean editing
five files and hoping; now it means editing one line below.

WHAT IS CANONICAL AND WHAT IS BUILT
-----------------------------------
Canonical, hand-authored, never regenerate:
    ORACLE_JSON             Caleb's card transcription — upstream source of truth
    RULES_DIR/*             the manual, glossary, rulebook, dev-logs
    SEED_RULINGS            hand-transcribed rulings

Generated — rebuild them, never hand-edit them:
    ORACLE_CORRECTIONS      <- the client's `npm run extract`
    COMPLEXITY_OVERRIDES    <- pipeline/classify_complexity.py
    MOD_ANCHORS             <- pipeline/build_anchors.py
    CORPUS                  <- pipeline/build_corpus.py
    GENERATED_RULINGS       <- pipeline/build_rulings.py
    ICONS_DIR/cost_*.webp   <- pipeline/build_cost_icons.py
    ICONS_DIR/once.webp     <- pipeline/build_cost_icons.py

These are names, not promises: nothing here creates a directory or asserts one
exists. Callers that write (store.py, the pipeline scripts) mkdir their own.

CONSTANTS vs FUNCTIONS, AND WHY THE SPLIT IS WHERE IT IS
--------------------------------------------------------
Everything above the "runtime state" section is a CONSTANT: it names committed,
read-only data whose location is a fact about the repository. Everything in
that last section is a FUNCTION reading ALGO_VAR_DIR, because it names live
data a test must be able to point somewhere else. See the ⚠ down there.
"""

import os
from pathlib import Path

#: this file, i.e. bot/
BOT_DIR = Path(__file__).resolve().parent
#: the repository root, one level above bot/
REPO_ROOT = BOT_DIR.parent

# ── shared data: read by BOTH the Python bot and the TypeScript client ───────
# The client reaches these over its own constants (engine/paths.ts, ui/assets.ts)
# and serves the card art and icons as static routes. Keep the two sides in step.
DATA = REPO_ROOT / "data"

CARDS_DIR = DATA / "cards"
ORACLE_JSON = CARDS_DIR / "AlgomancyCards-OracleText.json"
MOD_ANCHORS = CARDS_DIR / "mod_anchors.json"
#: GENERATED by the client's `npm run extract` from
#: client/engine/scripts/printed-overrides.mjs — the corrections this repo
#: carries against the canonical transcription above, for the readers that are
#: not the client. Applied on load by oracle.py; see its docstring for why the
#: bot was serving an uncorrected type line until 2026-09-01. Never hand-edit.
ORACLE_CORRECTIONS = CARDS_DIR / "oracle-corrections.json"
#: GENERATED by pipeline/classify_complexity.py: the Simple/Complex reading of
#: the type-bar icon on each scan, for the cards the oracle file leaves as the
#: placeholder `Common` (all of Light & Dark). Consumed by the client's
#: `npm run extract`, which is why paths.mjs names it too. Never hand-edit.
COMPLEXITY_OVERRIDES = CARDS_DIR / "complexity-overrides.json"
ICONS_DIR = DATA / "icons"
RULES_DIR = DATA / "rules"

# ── the RAG corpus and the rulings it is built from ─────────────────────────
CORPUS_DIR = DATA / "corpus"
CORPUS = CORPUS_DIR / "algomancy_corpus.jsonl"

RULINGS_DIR = DATA / "rulings"
SEED_RULINGS = RULINGS_DIR / "seed_rulings.jsonl"
GENERATED_RULINGS = RULINGS_DIR / "generated_rulings.jsonl"
RULINGS_EXPORTS = RULINGS_DIR / "exports"       # untracked: raw Discord dumps
NEEDS_OCR = RULINGS_DIR / "needs_ocr.jsonl"     # untracked: image-only messages

# ── the bot's own things ────────────────────────────────────────────────────
WEB_DIR = BOT_DIR / "web"          # the FastAPI app's front-end, still served at /static

# ── runtime state: append-only, gitignored, and the only copy there is ──────
# responses/feedback are the training + eval record; games.jsonl is real user
# state that combos.py reads back. Back these up; never commit them.
#
# ⚠ THESE ARE FUNCTIONS, AND EACH READS ITS ENV VAR ON EVERY CALL.
#
# They used to be module-level constants, and the bot's tests therefore wrote to
# the REAL log directory: the puzzle feature's `test_wtp.py` POSTed to
# /api/wtp/attempt, which reached store.log_wtp, which appended to
# var/logs/wtp_attempts.jsonl — on whatever machine the suite was run,
# INCLUDING THE DEPLOY BOX. It was recorded as pre-existing in d73ffd0
# ("running the bot suite on the deploy box touches live data") and not fixed.
# Measured 2026-09-01 before fixing it: 136 of the 247 rows in that file came
# from the test's own session ids (`t1`, `fresh-user`, `someone-else`) — 55% of
# a file that cannot be rebuilt.
#
# ⚠ THE EXAMPLE IS GONE AND THE RULE IS NOT. The puzzle feature was removed on
# 2026-09-02, so neither that test nor that log exists any more. Every path
# below is still a function, for exactly the reason above.
#
# The client side had the identical problem and solved it this way; see
# client/server/statepaths.ts, whose ⚠ says the same thing at more length. A
# test points ALGO_VAR_DIR at a scratch directory and everything below follows,
# because `var/` is one rule rather than five paths.
#
# Read at CALL time, not captured at import, for the reason statepaths.ts
# learned the hard way: a test that sets the variable in-process — after the
# module is already imported — would otherwise be silently ignored and would
# write to the real file while believing it had been redirected. A constant
# cannot be overridden late; a function can.

def var_dir() -> Path:
    """Every mutable thing this deployment owns; gitignored in full."""
    override = os.environ.get("ALGO_VAR_DIR")
    return Path(override) if override else REPO_ROOT / "var"


def log_dir() -> Path:
    return var_dir() / "logs"


def responses_log() -> Path:
    """Every AI answer with its full retrieval context — the training record."""
    return log_dir() / "responses.jsonl"


def feedback_log() -> Path:
    """👍/👎 on an answer, joined back by response_id."""
    return log_dir() / "feedback.jsonl"


def general_feedback_log() -> Path:
    return log_dir() / "general_feedback.jsonl"


def games_log() -> Path:
    """Which colour combos each person has played; combos.py reads it back."""
    return log_dir() / "games.jsonl"




# ── the Discord side's own state ──────────────────────────────────────
#
# ⚠ THESE ARE THE FIRST REWRITABLE FILES THE PYTHON SIDE OWNS. Everything in
# store.py is append-only JSONL, where a torn write costs one line. These are
# rewritten whole, so a truncated file silently disables the feature it
# configures. Whoever writes them must write to a temp file and rename, and
# whoever reads them must treat a corrupt file as empty rather than raising —
# a state file must never be able to stop the bot from booting.

def bot_state_dir() -> Path:
    return var_dir() / "discord"


def tree_sig_file() -> Path:
    """Hash of the slash-command tree as last synced GLOBALLY, so a restart
    does not re-sync an unchanged tree into a rate limit."""
    return bot_state_dir() / "tree.json"


def queue_watch_file() -> Path:
    """channel_id -> {guild_id, role_id} for the matchmaking-queue announcer."""
    return bot_state_dir() / "queue_watch.json"


# ── build-time only ───────────────────────────────────────────────────

def cost_icon_font() -> Path | None:
    """A bold Times-metric serif for pipeline/build_cost_icons.py, wherever this
    machine keeps one. The script used to hard-code the Debian path — the only
    absolute path on the Python side, and one the dev laptop does not have, so
    the icons could be rebuilt on the deploy box and nowhere else."""
    for candidate in (
        "/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf",
        "/usr/share/fonts/liberation/LiberationSerif-Bold.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSerif-Bold.ttf",
        "/usr/share/fonts/TTF/LiberationSerif-Bold.ttf",
        "/Library/Fonts/Times New Roman Bold.ttf",
        "C:/Windows/Fonts/timesbd.ttf",
    ):
        if Path(candidate).exists():
            return Path(candidate)
    return None
