/* Card definition DSL (docs/04 §5): declarative defs over effect primitives.
 *
 * Printed data comes from printed.json (generated by scripts/extract-printed.mjs
 * from AlgomancyCards-OracleText.json — never hand-copied). Only behavior is
 * authored here.
 *
 * Effects are code, but stack items must be serializable state — so a stack
 * item references its effects by string keys resolved through the registry:
 *   spell:<Card>       the card's spell effect
 *   ability:<Card>#<i> the effect of abilities[i]
 *   graft:<Card>       the card's [Switch]-marked transferable effect
 *   augment:<Card>#<i> the effect of augmentText[i] (text-box [Augment] text)
 */
import type {
  Attr, CardName, EffectPart, EngineEvent, Entity, EventType, Seat, StackItem, TargetRef,
} from '../types.ts';
import type { E } from '../engine.ts';
import printedJson from './printed.json' with { type: 'json' };

export interface Printed {
  name: string;
  /** element factions ("fire"; two for hybrids; [] / absent for synthetics) */
  factions?: string[];
  cost: string;                     // affinity pips, e.g. "rr"
  mana: number | 'X';
  power: number;
  toughness: number;
  type: string;
  kind: 'unit' | 'spell' | 'spellUnit' | 'spellToken';
  timing: 'deploy' | 'battle' | 'haste';
  attrs: Attr[];
  virus: boolean;
  burst: boolean;
  /** {Unstable} printed on the TYPE LINE (Aberrant Statweaver, Oorblak). Its
   * own flag, not an `Attr`, for the same reason `Entity.unstable` is not one
   * (types.ts): Unstable is a bin REPLACEMENT, not a combat attribute. Read by
   * `E.isUnstable` as the fourth way in (report #89 — a printed-Unstable card
   * used to bin like anything else, because nothing carried the marker). */
  unstable?: boolean;
  augmentAttrs: Attr[];             // type-line [Augment] grants (mods.py rule)
  /** "[Battle] Ambush [4bb]" alternative play mode: mana + affinity pips */
  ambush?: { cost: string; mana: number };
  /** Light & Dark: the printed "[2] Prophecy — Two Turns Pass" banner beneath
   * the title — an alternative cost + the condition that releases it. Stripped
   * out of `text` by the extractor. A prophecy GRANTED by rules text (e.g.
   * "It gains 'Prophecy — One Turn Passes'") is not a printed banner. */
  prophecy?: { mana: number; condition: string };
  /** Light & Dark: a printed "[Gain 4 debt]" bracketed additional cast cost
   * (its own line in the text box). Stripped out of `text`. */
  gainDebt?: number;
  /** R40: the printed "Discard me" cost line — an alternative play mode like
   * Ambush ("1 Discard me" on Dropslime, "2 [d] Discard Me. {Battle}" on
   * Nothyr): pay this cost, discard the card from hand, and the resulting
   * TRASH fires the card's own "when I am trashed" trigger. `timing` is the
   * timing of THIS MODE when the line carries its own marker — Nothyr's
   * {Battle} sits on the discard-me line while the card itself is a deploy
   * unit. Stripped out of `text` by the extractor. */
  discardMe?: { cost: string; mana: number; timing?: 'battle' };
  text: string;
  image: string;
}

/** A resolved 'cachedCard' target: the entry is looked up by its stable uid at
 * RESOLUTION, so `card` is what is actually sitting there now. Effects act on
 * it through E.cacheIndexOf(seat, uid). */
export interface ResolvedCached { cached: { seat: Seat; uid: number; card: CardName } }

/** Resolved target passed to effect run(): an entity, a player, a stack item
 * id, or a cached card. */
/** R64: a resolved 'binCard' target. `index` is where it sits in that bin at
 * the moment of resolution — looked up then, never carried from cast. */
export interface ResolvedBin { binCard: { seat: Seat; index: number; card: CardName } }

export type ResolvedTarget = Entity | { player: Seat } | { stack: number } | ResolvedCached | ResolvedBin;

export interface EffectCtx {
  controller: Seat;
  sourceName: string;
  sourceId?: number;
  region: number;
  targets: ResolvedTarget[];
  x?: number;
  /** receipt of this part's cast-time [cost] payment (R35) — e.g. the unit
   * sacrificed to cast, with its stats snapshotted at payment time */
  costPaid?: EffectPart['costPaid'];
  /** {Modular}: the mods applied to this card as it was played (Spellbind).
   * A GRAFTABLE mod's effect already rides as an extra part; any mod's
   * type-line [Augment] attributes reach `grantedAttrs` below (R105). This is
   * the readable list, for text that wants to know what is attached — and
   * under R105 it may hold a card that contributes neither. */
  mods?: CardName[];
  /** R79/R105: attributes something applied to this effect donates to it — a
   * VIRUS augmented onto it while it sat on the stack (Chitin Shredder's
   * {Powerful} on a Fireball), or a {Modular} mod applied to it as it was
   * played. Only type-line `[Augment]` attributes ever appear here — a spell
   * has no body for a static or a triggered ability. `E.dealEffectDamage`
   * unions these into the source's printed attrs; anything else that judges an
   * effect by its attributes should read them the same way. */
  grantedAttrs?: Attr[];
  /**
   * The printed "Erase me." / "Erase this spell." clause on a SPELL —
   * Collect Remains, Suspend, Temporal Rift.
   *
   * "Me" is the stack item currently resolving, and by the time an effect runs
   * its card is already off the stack and on its way to a bin — `resolveTop`
   * popped it, and `E.dischargeItem` will place it once every part has run. So
   * this does not erase anything itself: it raises `StackItem.eraseSelf`, and
   * the disposal reads it and sends the card to the erased pile (R65) instead
   * of the bin. Calling it twice is the same as calling it once.
   *
   * CONSEQUENCES OF LIVING IN THE EFFECT, all of them deliberate (see
   * `StackItem.eraseSelf`): a NEGATED spell never runs its parts, so it never
   * asks, so it is binned — R68 says the effect does nothing, and this clause
   * is part of the effect. A part that FIZZLES for want of a target (R5) is
   * the same. Contrast R79's {Unstable}, which is a stamp on the card and
   * outlives both.
   *
   * Only a kind that HAS a card to place responds to it — a spell. A trigger
   * or an activated ability has no card of its own (its `card` names a source
   * still standing in play), so asking there does nothing. A unit erasing
   * ITSELF in play is a different mechanism: see `AbilityCost.eraseSelf`
   * (Skybreaker) and the card-side erase helpers (Spore of Regenesis).
   */
  eraseSelf: () => void;
  /**
   * CARD-TODO #18 — "I did nothing; do not spend the [once]."
   *
   * A `bounded` ability ([once] / [Switch1], R9) reserves its budget when the
   * trigger is COMPOSED, before the run exists. The reservation stays there —
   * it is the re-entrancy guard — and this is the way back out.
   *
   * SUPERSEDED BY R113 — read that first. The sentence below is the owner's
   * first pass; the designer later narrowed it to "declined, or no offer was
   * possible", which is NOT the same as "did nothing". Calling this from a
   * branch that merely whiffed is now a bug (94-bounded-uses guards it).
   *
   * RULED 2026-08-23 (owner): "A [once] is spent only when the ability
   * actually does something. Say no to a 'you may' and the budget is intact,
   * so the same trigger can ask again later the same turn." That covered both
   * halves of the defect at once: the ORDINARY decline, and the never-asked
   * auto-decline that Hexbane Shiitake used to take during the end-of-turn
   * window, where the [once] burnt on a question nobody was asked. The
   * auto-decline is gone now — every such card ASKS, wherever it resolves
   * (99-endofturn.test.ts) — so only the ordinary decline is left, and it
   * refunds.
   *
   * CALL IT FROM a branch that DECLINED or found NOTHING TO DO. Do NOT call it
   * from a branch that mutated state, even partially: half a job is a job, and
   * a refund there would make `[once]` mean nothing.
   *
   * Optional because not every EffectCtx has a budget behind it — a card
   * played inline mid-resolution has no stack item and no composed part — so
   * card code calls it as `ctx.refundBudget?.()`. Calling it on an ability
   * that is not bounded is a no-op: there is no reservation to hand back.
   * Calling it twice is the same as calling it once.
   */
  refundBudget?: () => void;
  /** R1: the event snapshot for triggered abilities (conditions were checked at
   * event time; amounts must be computed here, at resolution, from live state) */
  event: EngineEvent | null;
  /**
   * R57: the half of a MODAL effect the caster declared in the cast window
   * (see `EffectDef.modes` and `EffectPart.mode`). Card code reads it and
   * branches — it never asks, because by the time `run` is entered the answer
   * has been on the stack for the whole response window.
   *
   * `null` when there was nothing to choose between (an empty `options`);
   * `undefined` on an effect that declares no `modes` at all.
   */
  mode?: unknown;
  /** mid-resolution choice (R4 electric path, R6 payments). Returns the stored
   * answer or suspends the engine with a decision. Parts that use this must
   * request all choices before mutating state, or use plan-then-commit —
   * the engine rolls back to the part boundary on suspension. */
  choose: (key: string, dec: { kind: 'payOrDecline' | 'electricPath'; seat: Seat; prompt: string; options: { label: string; value: unknown; card?: CardName }[] }) => unknown;
}

export interface TargetSpec {
  /** 'cachedCard' (R41): a card in EITHER player's cache — the zone is public
   * information, so both are legal targets, and it is not region-scoped.
   * (Prismatic Observer: "Recall up to one target cached card".) */
  /** R60 — "target effect" vs "target SPELL effect". The card set draws the
   * line itself: three cards say "target spell effect" (Dreadwave Devourer,
   * Null Drone, Dream Lapse) and one says "target NONSPELL effect" (Nothyr).
   * Both qualifiers would be dead words if plain "effect" meant only spells,
   * so plain "effect" is the SUPERSET.
   *   'stackSpell'  — spell / spell unit / spell token / ambush. The cards
   *                   that spell out "spell effect".
   *   'stackEffect' — all of the above PLUS triggered and activated abilities
   *                   and viruses: anything on the stack that is an effect.
   *                   The cards that just say "effect".
   * A UNIT on the stack is in neither: a unit arriving in play is not an
   * effect, and it has no parts to negate. */
  /** R64 — the OWNERSHIP kinds. 'allyUnit'/'enemyUnit' are relative to the
   * effect's controller, never to the chooser: a redirect that drops a unit
   * into someone else's "target ally" slot is what R58 already refuses.
   * 'opponent' is a PLAYER-only kind ("target opponent" — Ralph, Interdiction
   * Rift, Divine Foresight); 'player' is the same kind WITHOUT the ownership
   * clause — plain "target player" (Soul Siphon), which may legally be
   * yourself; 'any' offers units and players together and is the damage kind,
   * not a substitute for either.
   * 'token' is any token in the region, unit or spell token (Arcane Echo,
   * Download) — a token is a legal target for these whoever controls it, and
   * "gain control of" narrows to the enemy half with `restrict`. */
  what: 'unit' | 'allyUnit' | 'enemyUnit' | 'token' | 'any' | 'opponent' | 'player'
    | 'stackSpell' | 'stackEffect' | 'cachedCard'
    /** R64: a card in YOUR bin ("target unit … from your bin"); 'anyBinCard'
     * reaches either player's, which is what "target card in a bin" prints. */
    | 'binCard' | 'anyBinCard';
  prompt: string;
  /** maximum number of targets chosen AT CAST TIME (default 1). Distinct
   * targets; the chooser gets a "done" option once `min` are picked.
   * R64: `'X'` means the spell's X — the mana X it was cast for, or the
   * amount a variable bracketed cost was paid at ("Negate up to X target
   * effects", "Recall X target nontoken allies"). X is fixed before targets
   * are asked for, so by the time this is read it is a number. */
  count?: number | 'X';
  /** minimum targets before "done" is offered (default 1) */
  min?: number;
  /**
   * R83: fixed slots asked for IN ADDITION to `count`, so a spec can mix a
   * variable-count slot with a fixed one. Channel Through prints "I deal 2
   * damage to each of X target allies. For each ally damaged this way,
   * distribute 2 damage among target opponent's units" — X allies AND one
   * opponent, and until this existed the opponent simply went undeclared.
   *
   * The extra slots come FIRST, at indices 0…extraSlots-1, which is what
   * `slots` (an ABSOLUTE index) already describes: `slots: ['opponent']` with
   * `what: 'allyUnit'` makes slot 0 the opponent and every later slot an ally.
   * First rather than last for a mechanical reason, not a stylistic one — a
   * counted spec ends when the chooser says "no more targets", and a slot
   * behind that gate could never be reached.
   */
  extraSlots?: number;
  /** R58: per-SLOT restriction for a multi-target spec — `slots[i]` governs
   * target i and falls back to `what`. Fight prints "target ally and ANOTHER
   * target unit": two cast-time targets whose legality differs by slot
   * (['allyUnit', 'unit']). Without this a two-target spec could only ask one
   * question twice, which is how Fight ended up choosing its second target
   * mid-resolution instead. */
  slots?: TargetSpec['what'][];
  /** R58: per-slot prompt, same indexing as `slots`; falls back to `prompt`. */
  slotPrompts?: string[];
  /**
   * R64 — the RESTRICTION seam. "Delete target unit with base power 2 or
   * less", "recall target unit with 5 or less defense", "target unit with no
   * stat changes": the printed restriction is part of what makes a target
   * LEGAL, not a condition checked once the spell resolves. Without a seam
   * every such card offered the whole board and then did nothing, which is
   * indistinguishable from a bug at the table.
   *
   * The predicate runs against the RESOLVED target, so it can read live stats,
   * counters, controller and card data. It is asked in three places and they
   * must agree: the candidate list you choose from, `castable` (no legal
   * target ⇒ the cast is illegal), and `canFillSlot` (a redirect may not drop
   * an illegal target into the slot). It is NOT re-asked at resolution — R5
   * and R56 govern that, and a card whose restriction can change between cast
   * and resolution re-checks it in `run` (Unmake, Reconfigure).
   */
  restrict?: TargetRestrict;
  /** R64: per-slot restriction, same indexing as `slots`; falls back to
   * `restrict`. Use `null` in a slot to mean "this slot has none". */
  slotRestricts?: (TargetRestrict | null)[];
}

/** R64: the context a TargetSpec.restrict is judged in — whose effect this is,
 * where it is being cast, and (for "another target …") which entity is its
 * source. `ally` is the effect's controller: the seat "ally"/"enemy" is
 * measured from. */
export interface TargetCtx {
  ally?: Seat;
  region: number;
  sourceId?: number;
  /** the item's X, already fixed by the time targets are asked for (R64) —
   * "target unit with cost [x] or less" (Abduct) has nowhere else to read it */
  x?: number;
  /** R64: the targets ALREADY chosen for this part, resolved. A later slot
   * whose legality depends on an earlier one reads them here — Necromorph's
   * second target is "with cost less than or equal to IT". */
  chosen?: ResolvedTarget[];
  /**
   * R67: the event that FIRED this ability, for a triggered ability whose
   * printed target is phrased relative to it — Rippleback Skulker's "put
   * target card from THAT PLAYER's bin into your hand" cannot say which bin
   * without knowing who was just dealt combat damage.
   *
   * Null/undefined for a spell or an activated ability: they have no event.
   * It is the same snapshot the effect later reads as `ctx.event`, so a
   * restriction and the run() it gates agree about what happened.
   */
  event?: EngineEvent | null;
}

/** R64: a printed targeting restriction, as a predicate over the resolved
 * target. Returns true if `t` may legally be chosen. */
export type TargetRestrict = (g: E, t: ResolvedTarget, ctx: TargetCtx) => boolean;

/** R58: the restriction governing target slot `i` of a spec. */
export function slotWhat(spec: TargetSpec, i: number): TargetSpec['what'] {
  return spec.slots?.[i] ?? spec.what;
}

/** R64: is this resolved target an ENTITY (a unit, a token, a mod)? The other
 * resolved shapes — a player, a stack item, a cached card, a bin card — carry
 * no id. */
export function isEntityTarget(t: ResolvedTarget): t is Entity {
  return 'id' in t && 'card' in t;
}

/**
 * R64: the common shape of a printed targeting restriction — a clause about
 * the UNIT ("with base power 2 or less", "with no stat changes", "with 5 or
 * less defense"). Non-unit targets pass through untouched, so a spec that
 * offers units and players alike still offers the players.
 */
export function unitRestrict(ok: (g: E, u: Entity, ctx: TargetCtx) => boolean): TargetRestrict {
  return (g, t, ctx) => !isEntityTarget(t) || ok(g, t, ctx);
}

/** R64: "with cost N or less" / "with cost less than or equal to …" — read off
 * the PRINTED mana cost, which is what "cost" means on every card that says
 * it. An X card counts as 0, its printed floor. */
export function printedCost(name: CardName): number {
  const m = getCard(name).mana;
  return m === 'X' ? 0 : m;
}

/** R64: "another target …" — a slot that may not be the effect's own source.
 * Distinctness BETWEEN slots is already enforced by the collector; this is the
 * separate clause that excludes the unit the ability is printed on. */
export const notSelf: TargetRestrict = (_g, t, ctx) =>
  !isEntityTarget(t) || ctx.sourceId === undefined || t.id !== ctx.sourceId;

/** R64: the restriction governing target slot `i` — `slotRestricts[i]` when
 * the spec names one (including an explicit `null` for "no restriction here"),
 * otherwise the spec-wide `restrict`. */
export function slotRestrict(spec: TargetSpec, i: number): TargetRestrict | undefined {
  const per = spec.slotRestricts?.[i];
  if (per !== undefined) return per ?? undefined;
  return spec.restrict;
}

/** R58: the spec as it applies to slot `i` — what targetCandidates should be
 * asked for when filling that one slot. */
export function specForSlot(spec: TargetSpec, i: number): TargetSpec {
  const r = slotRestrict(spec, i);
  return { ...spec, what: slotWhat(spec, i), ...(r ? { restrict: r } : { restrict: undefined }) };
}

/**
 * A bracketed additional cost ("[Sacrifice a unit]: …", "[Pay 3 life]",
 * "[Discard a card]", "[Gain 4 debt]", "[Remove X +1/+1 counters from
 * allies]") chosen and PAID AT CAST, before the item reaches the stack (R35).
 * An unpayable cost makes the cast ILLEGAL; on a grafted rider it is optional
 * and declining skips that part.
 *
 * `n` is the amount. `'X'` (R64) is a VARIABLE cost: the payer keeps paying
 * one unit at a time until they stop, and the number they paid IS the spell's
 * X — Discharge's "[Remove X +1/+1 counters from allies]: I deal X damage"
 * has no other source for X. A variable cost is offered down to `xMin`
 * (default 0, i.e. "you may decline outright and the spell does nothing");
 * the amount paid lands in `costPaid.x` and reaches the effect as `ctx.x`.
 *
 * 'payLife' is governed by R49: you may pay N life only while you have MORE
 * than N — a cost you cannot survive is not payable.
 */
export type CastCost =
  | { kind: 'sacrificeUnit' }
  /**
   * "[Sacrifice X units]" (Malevolent Machinations) — `n` units, or 'X'.
   *
   * `from: 'self'` is "sacrifice **me**" (Eldritch Dreamtender), resolved
   * through `item.sourceId` exactly as `removeCounters`' own `from: 'self'`
   * is. It carries NO choice — there is nothing to pick — so it is charged
   * outright in the cast window with no decision and no suspension, which is
   * what keeps it unrespondable. `n` must be 1. A source that is already dead
   * makes it UNPAYABLE, so R5 partial resolution skips the part: a trigger
   * whose source died between firing and settling does nothing at all.
   *
   * `includeSelf` is "sacrifice ME AND another ally" (Deformant) — the source
   * plus `n - 1` others, as ONE indivisible payment. It is not `from: 'self'`
   * with a second cost bolted on and it is not "any n units": the source is
   * MANDATORY and is excluded from the menu the rest is chosen from. Charged
   * in two halves in the one cast window — the choice-free source first,
   * through the same branch `from: 'self'` uses, then the loop for the rest —
   * and payability demands BOTH halves UP FRONT, or the source would die for
   * a cost whose remainder cannot be paid.
   */
  | { kind: 'sacrificeUnits'; from?: 'self'; includeSelf?: true; n: number | 'X'; xMin?: number }
  | { kind: 'payLife'; n: number | 'X'; xMin?: number }
  | { kind: 'discardCard'; n: number | 'X'; xMin?: number }
  | { kind: 'gainDebt'; n: number }
  /** "[Remove X +1/+1 counters from allies]" (Discharge) / "from me" (Soul
   * Reaver). `from: 'self'` spends the SOURCE unit's own counters. */
  | { kind: 'removeCounters'; from: 'allies' | 'self'; n: number | 'X'; xMin?: number }
  /** "[Erase X cards from your bin]" (Necromantic Rebuke) */
  | { kind: 'eraseBin'; n: number | 'X'; xMin?: number };

/** R64: the fixed amount a cost demands, or null when it is variable ('X'). */
export function costAmount(cost: CastCost): number | null {
  if (cost.kind === 'sacrificeUnit') return 1;
  if (cost.kind === 'gainDebt') return cost.n;
  return cost.n === 'X' ? null : cost.n;
}

/** R64: the floor a variable cost may be paid down to (default 0). */
export function costXMin(cost: CastCost): number {
  return ('xMin' in cost ? cost.xMin : undefined) ?? 0;
}

/**
 * R57 — a printed MODAL clause: "[Put a -1/-1 counter on each enemy or put a
 * +1/+1 counter on each of your units]", "[gains or loses] X life", "double
 * target unit's power or defense". The caster picks a half, and the pick is a
 * CAST-TIME declaration, collected by `E.collectModes` alongside X, mods,
 * targets and costs and stored on the part as `EffectPart.mode`.
 *
 * DECLARED PER EFFECT, not per card, because a graft composite asks per part:
 * Wither and Bloom, Burgeon and Spirit of Nature are all `graftEffect`s, and a
 * Burgeon grafted onto a Burgeon is two parts with two independent halves.
 *
 * `prompt` and `options` are computed from the item as it stands at the end of
 * the cast window — X is fixed, the targets are named — so Burgeon's options
 * can read the unit it is aimed at ("Power (5 → 10)"). They must be PURE: the
 * cast window re-runs from the top after every answered decision, so they are
 * called more than once and must not mutate anything.
 *
 * Fewer than two options is not a question: `collectModes` records the single
 * value (or `null` for none) without asking, which keeps `part.mode`'s
 * presence a sound idempotence guard.
 */
export interface ModeSpec {
  /** a name for the choice, for logs and for the ledger — 'mode', 'stat', … */
  key: string;
  prompt: (g: E, item: StackItem, part: EffectPart) => string;
  options: (g: E, item: StackItem, part: EffectPart) => { label: string; value: unknown }[];
}

export interface EffectDef {
  targets?: TargetSpec;
  /** R57: this effect is MODAL — the caster declares which half in the cast
   * window, and `run` reads the answer back as `ctx.mode` (see ModeSpec). */
  modes?: ModeSpec;
  /** cast-time additional cost (R35). On a spell: paying is part of casting —
   * with nothing to pay the cast is illegal. On a graft part joining a
   * composite: the carrier's controller pays (or declines — the rider is then
   * skipped) when the composite collects its cast-time decisions, exactly
   * where graft targeting happens. The receipt lands in ctx.costPaid. */
  castCost?: CastCost;
  /**
   * R74 — a VARIABLE cast cost ('X') whose **X = 0 makes this effect a
   * guaranteed no-op**, said in one line and DECLARED rather than discovered.
   * The engine shows it on the "That's enough — X = 0" option at the moment
   * the payer can stop at zero, and logs it if the cost closes at zero on its
   * own (an empty pool).
   *
   * It is a WARNING, never a prohibition — X = 0 stays legal and the option is
   * still offered. That is the deliberate difference from `CastCost.xMin`,
   * which forbids: use `xMin` where paying zero would burn something the payer
   * cannot get back (No Hand Killer's `[once]` budget), and this where paying
   * zero is merely a bad idea you are allowed to have.
   *
   * Declared per effect because "X = 0 does nothing" is a fact about the
   * EFFECT, not about the cost kind: Necromantic Rebuke's ransom is trivially
   * met at X = 0, Discharge deals 0 damage, Flesh Tithe makes no unit,
   * Malevolent Machinations negates nothing. All four already say so at
   * RESOLUTION, which is far too late to be of use.
   */
  xZeroWarning?: string;
  /** R5: if true, all targets invalid at resolution fizzles the whole effect.
   * Default: resolve partially against remaining legal targets. */
  allOrNothing?: boolean;
  /** Every token this effect can put onto the board, DECLARED rather than
   * inferred. The inspector's "tokens it creates" panel used to scrape the
   * PRINTED text for a registered token name, which is wrong three ways: it
   * misses plurals ("Create three Wraiths"), it cannot see a token whose card
   * is also in DECK_LIST (Echo of Despair, Hooba-God), and printed text is the
   * card's history, not its rules (R63 granting, donated mod text and graft
   * composites are all invisible to it). A declaration is checked against what
   * the effect actually does by the conformance test, so a card that starts
   * making a token and forgets to say so fails `npm test`. */
  creates?: string[];
  /**
   * R69, the honest escape hatch: this effect's token NAME is COMPUTED, not
   * printed — it copies whatever token it is pointed at (Arcane Echo's "create
   * a copy of target token", Automaton of Abundance's duplication of any unit
   * token you create). No fixed `creates` list can be true for those, and the
   * conformance test would rather be told that than be handed a guess.
   *
   * It exempts the effect from the "recorded ⊆ declared" assertion, so use it
   * ONLY where the name genuinely cannot be known before resolution — an
   * effect that picks among a KNOWN set (Cosmic Conspirator's Poison/Crystal/
   * Fireball, Spirit of Nature's Poison-or-Crystal) declares that set instead.
   * The test still checks that whatever such an effect spawns is a registered
   * card, and `createsOf` deliberately does NOT report it: the inspector must
   * not claim a card makes Wraiths merely because it could copy one.
   */
  createsAny?: boolean;
  /**
   * R110 — "[Switch1][Switch1] (Trigger two copies of this graft ability as
   * one single trigger)": this effect is a graft MULTIPLIER. Lost Guardian
   * (2), Witness of the Crossing (3) and Amphivore (3) declare it; they do
   * nothing themselves. composeParts materializes every OTHER graft part of
   * the composite this many times, top-to-bottom and then top-to-bottom
   * again (Graft 1 → Graft 2 → Graft 1 → Graft 2), as ONE stack item:
   *   - bounded ([Switch1]) grafts are repeated too — the cause's single
   *     trigger spends the graft's budget once and gets N copies of it;
   *   - a "[cost]: effect" graft must pay its cost N times, in the cast
   *     window, and if it cannot pay all N it pays nothing and the effect
   *     does not happen at all (collectCastCosts);
   *   - each copy is its own part: its own targets, its own cost receipt.
   * Source: Insanity Engine (moderator) 2025-03-21, "Amphivore / Lost
   * Guardian. Bounded Grafts and Ralph explained." Two multipliers in one
   * composite multiply (unruled; no pool card can reach it without a
   * doubler grafted under a doubler).
   */
  graftCopies?: number;
  run: (g: E, ctx: EffectCtx) => void;
}

export interface TriggeredAbility {
  type: 'triggered';
  events: EventType[];
  /** only fire when the event's source is this entity */
  self?: boolean;
  /**
   * R51: the trigger listens while the CARD SITS IN THIS ZONE rather than
   * while it is a unit in play ("If I am in your bin, after combat …" —
   * Lurking Dread, Inexorable Miasma, Cinder Scuttler). fireEvent() scans
   * entities in play and a card in a bin is not one, so these are dispatched
   * separately, anchored on a DETACHED stand-in entity with id -1 (exactly
   * like R40's fireOwnTrashTrigger): `self` is not a real unit, it cannot be
   * targeted, it radiates no statics and its bounded budget lives only for
   * the one firing. `when` receives that stand-in with `owner`/`controller`
   * set to the zone's seat, so "if I am in YOUR bin" is ctx.controller.
   *
   * Only ONE copy of the card fires per zone per event even if the zone holds
   * several — the printed cards are all "if I am in your bin", a single
   * standing permission, not a per-copy trigger.
   */
  zone?: 'bin' | 'cache';
  /** R1: condition — evaluated once, at event time */
  when?: (g: E, self: Entity, ev: EngineEvent) => boolean;
  label: string;
  /** [Switch1]: once per turn, tracked per card (R9) */
  bounded?: boolean;
  /** carries a graft symbol => is a graft cause (grafts can attach to it) */
  graftCause?: boolean;
  effect: EffectDef;
}

/**
 * R49: what activating an ability costs. Every one of these GATES the
 * activation — an ability whose cost cannot be paid is not offered by
 * legalActions and is refused by apply() — instead of fizzling at resolution.
 *
 *  - mana / life / debt / sacrificeSelf / eraseSelf carry no choice, so
 *    doActivateAbility pays them outright, before the item is built.
 *  - discard / sacrificeOther carry a choice, so they ride on the item as
 *    `pendingCosts` and are chosen in the cast window, still before the item
 *    reaches the stack: no one may respond between cost and effect.
 *
 * `life` obeys R49: payable only while you have MORE life than it costs.
 */
export interface AbilityCost {
  mana?: number;
  sacrificeSelf?: boolean;
  /**
   * The printed "Erase me:" activation cost — Skybreaker's
   * "[Augment] Erase me: Negate all spell effects."
   *
   * Distinct from `sacrificeSelf`, and the difference is the whole reason it
   * exists: a sacrifice is a DEATH (the unit dies, its card reaches a bin,
   * every "when a unit dies" trigger fires and R40 can trash it out of the bin
   * afterwards), while an erase removes the unit from the game outright — no
   * bin, no death, no despawn, so nothing triggers off it at all. Skybreaker
   * was `sacrificeSelf` as a stand-in and was therefore recurrable out of its
   * own bin, which the printed card does not allow.
   *
   * Choice-free like `sacrificeSelf`, so `E.payActivationCost` pays it in the
   * cast window, and — also like `sacrificeSelf` — it gates nothing: the
   * source unit is what is being erased, and an ability is only ever offered
   * while its source is in play.
   */
  eraseSelf?: boolean;
  /** "Pay N life:" */
  life?: number;
  /** "Gain N debt:" */
  debt?: number;
  /** "Discard a card:" — N cards from your hand */
  discard?: number;
  /** "Sacrifice a unit:" — N units you control OTHER than the source */
  sacrificeOther?: number;
  /** "Discard a card OR sacrifice a nontoken unit:" — N payments, each of
   * which may be either a hand card or another NONTOKEN unit you control.
   * The one either/or shape the pool actually prints (Pallid Gorger,
   * Combustible Bogwalker, Lilbot); a general cost algebra is not worth it. */
  discardOrSacrifice?: number;
}

export interface ActivatedAbility {
  type: 'activated';
  cost: AbilityCost;
  /** R49: a printed "{Battle}" / "{Deployment}" marker ON THE ABILITY (Grox,
   * Cadaverous Cultivator). doActivateAbility gates by PHASE, so without this
   * a battle-only ability was activatable during deployment too. Absent = the
   * ability may be activated in either window, the standing behaviour. */
  timing?: 'battle' | 'deploy';
  label: string;
  bounded?: boolean;
  graftCause?: boolean;
  /**
   * R77 — a printed PRECONDITION on activating: "Activate this ability only
   * if …". A gate, not a fizzle: an ability whose condition is false is not
   * offered by legalActions and is refused by apply(), exactly the way R64
   * treats an unpayable [cost] or a target with nothing legal to aim at.
   *
   * `self` is the SOURCE unit — the host when the ability was donated by an
   * augment, so "I" reads correctly either way. Evaluated BEFORE any cost is
   * paid, which is what lets a condition about the source coexist with
   * `cost.sacrificeSelf`: the check has already happened by the time the
   * sacrifice removes its own subject.
   *
   * R1: this is a condition, so it is checked once, at activation. It is not
   * re-checked at resolution — for a self-sacrificing ability it could not be.
   */
  usableWhen?: (g: E, self: Entity, seat: Seat) => boolean;
  effect: EffectDef;
}

export type Ability = TriggeredAbility | ActivatedAbility;

/**
 * R118, the CONTINUOUS half of the copy layer: a card that radiates other
 * cards' FACES onto a unit — "[Augment] I have all abilities of adjacent
 * allies. (This includes modded abilities.)" (Ancient One).
 *
 * The additive twin of `Entity.copies`, and it has to be continuous rather
 * than a stamp for the reason the ledger entry gave: adjacency changes inside
 * a single combat (R72 column collapse, a neighbour dying, blockers being
 * declared), so the answer must be recomputed every time it is asked, exactly
 * as `StaticMod` is.
 *
 * Radiation rules are `StaticMod`'s, line for line: the `E.anchored()` walk
 * (units in play plus augment mods reading from their HOST — so the [Augment]
 * form projects onto the host and "I" is the host), the R12 region scope, and
 * the shallow R62 guard (a silenced projector radiates nothing).
 *
 * ⚠ A projected face contributes STATICS / ACTIVATED / TRIGGERED and nothing
 * else — never `name` and never `stats`. "I have all abilities of adjacent
 * allies" does not rename the Ancient One and does not make it a 7/5. The
 * engine enforces this: `facesOf()[0]` is always the identity face.
 *
 * ⚠ Same reentrancy contract as `StaticMod`, one step stricter: `faces` MUST
 * NOT READ A NUMBER. It runs inside the `facesOf` latch, from underneath
 * `effStats`, so a call into effStats/baseStatsOf would be reading the very
 * projection it is being asked to produce. Read geometry and raw fields only
 * (`E.adjacentInFormation`, `Entity.mods`, controllers) — the discipline
 * `statLayerAttrs` states as "the walk is ownAttrs, never effStats".
 */
export interface FaceProjection {
  /** which entity the faces land on. Default: the projector's own anchor,
   * which is the unit itself, or the HOST when the text arrived as an
   * augment mod. */
  onto?: (g: E, self: Entity, target: Entity) => boolean;
  /** the card names whose faces are projected. Duplicates are deduped by the
   * engine; the projector's own face is skipped (no recursive mimicry). */
  faces: (g: E, self: Entity) => CardName[];
  /** which facets each projected face contributes. Defaults to statics +
   * activated + triggered; `name` and `stats` are refused by the engine. */
  facets?: import('../types.ts').CopyFacet[];
}

/** A continuous ("static") modification a card projects while it is a unit in
 * play: "+X/+Y to matching units", granted attributes, or both. Evaluated live
 * inside effStats/ownAttrs (engine stat layer 3). affects() runs for units in
 * the SAME REGION as the holder (R12) — return true to include the holder
 * itself. IMPORTANT: affects/dp/dt must not call effStats (reentrancy guard
 * makes nested statics vanish); read raw fields (counters, hand sizes, card
 * data) instead. */
export interface StaticMod {
  affects: (g: E, self: Entity, target: Entity) => boolean;
  dp?: number | ((g: E, self: Entity, target: Entity) => number);
  dt?: number | ((g: E, self: Entity, target: Entity) => number);
  /**
   * LAYER 2, the CONTINUOUS half: while this static applies, the target's
   * BASE power/defense is REWRITTEN to this number — "Your units are base
   * 3/3" (Aberrant Statweaver). This is a replacement, not a delta: it is the
   * literal number on the card changing, so two Statweavers do not stack, a
   * 1/1 and a 7/5 both land on exactly 3/3, and every layer-3 change
   * (counters, until-regroup deltas, a lord's +1/+1) still applies ON TOP.
   *
   * Setting only one of the pair rewrites only that half. Read through
   * E.baseStatsOf, which resolves these against the until-regroup
   * `Entity.baseSet` stamp last-wins by timestamp — never by summing.
   *
   * Same reentrancy rule as dp/dt, one step stricter: baseP/baseT must not
   * call baseStatsOf or effStats either (the guard makes the nested query
   * return the printed base).
   */
  baseP?: number | ((g: E, self: Entity, target: Entity) => number);
  baseT?: number | ((g: E, self: Entity, target: Entity) => number);
  attrs?: Attr[];
  /**
   * R62, the CONTINUOUS half of the suppression layer: while this static
   * applies, the target's attribute layer (`suppressAttrs`) and/or its ability
   * layer (`suppressAbilities`) is switched off — "other units lose all
   * attributes and abilities during battle" (Monke), "[Augment] Your other
   * units gain +2/+2 and lose all attributes and abilities" (Transmogrifant).
   *
   * Suppression is subtractive where every other static is additive, so it is
   * read through E.suppressionOf(), never by summing: one suppressor is
   * enough, and no amount of granting outvotes it.
   */
  suppressAttrs?: boolean;
  suppressAbilities?: boolean;
  /**
   * R11, the CONTINUOUS half of the regroup cleanup: while this static
   * applies to a SPELL TOKEN, regroup does not erase it — "[Augment] Your
   * spell tokens stay through regroup" (Harbinger of Immolation).
   *
   * A static and not a trigger, and not a replacement hook either. The erase
   * is not an event: it is a step of the R11 cleanup sequence, so there is
   * nothing to put on the stack, nothing to respond to and nothing to negate,
   * and a trigger that "re-created" the tokens afterwards would be a
   * different card (new entities, new ids, the X re-derived). What the text
   * describes is a standing property of the tokens themselves — they are the
   * kind that stay — which is what layer 3 is for.
   *
   * Being a static is also what gets the [Augment] half right for free. The
   * clause is text-box [Augment] (live on the card played normally AND
   * donated to a host), and statics already anchor exactly that way: they
   * radiate from a unit in play and from an augment mod through E.anchored(),
   * reading from the HOST. So the donated form protects the HOST
   * controller's tokens with no extra code, the way a donated aura does.
   *
   * Read through E.spellTokenSurvivesRegroup(), never by summing: like
   * suppression this is a veto-shaped query, one protector is enough. It
   * spares the token from the ERASE and nothing else — startRegroup still
   * sweeps the token's temporary changes, and its X (the Fireball's number)
   * is not something regroup ever touched.
   *
   * ⚠ The target of this one is a spellToken, not a unit, so `affects` must
   * not assume `target.kind === 'unit'` the way the stat statics do.
   */
  survivesRegroup?: boolean;
}

/** What a cost modifier is being asked about. `purpose` separates PLAYING a
 * card from APPLYING it as a mod — applying a mod is not playing (R37, Bena's
 * ruling), so "spells cost [one] more to PLAY" must not tax an augment. */
export interface CostCtx {
  seat: Seat;
  card: CardDef;
  region: number;
  purpose: 'play' | 'mod';
}

/**
 * R59: a continuous COST modifier, radiating from a unit in play or from an
 * augment mod exactly like a StaticMod, and scoped to the holder's region
 * (R12). `delta` returns extra mana — negative to discount. The total is
 * clamped at zero: no card ever costs less than nothing.
 *
 * Like StaticMod, `delta` must not call anything that re-enters cost
 * evaluation (canPayCard / payCard / manaToPlay); read raw state instead.
 */
export interface CostMod {
  delta?: (g: E, self: Entity, ctx: CostCtx) => number;
  /**
   * R60: extra LIFE the play costs — "Cards played during battle gain
   * [Pay 2 life]" (Arbiter of Armistice). A separate channel from `delta`
   * because life and mana are not interchangeable: the mana half gates on
   * open resources, the life half on R49's canPayLife (you may pay N life
   * only while you have MORE than N), and an unpayable life tax makes the
   * card uncastable exactly as unpayable mana does.
   */
  life?: (g: E, self: Entity, ctx: CostCtx) => number;
}

/**
 * R94: what an `EffectAttrMod` is being asked about — ONE PART of ONE
 * resolving stack item.
 *
 * Per-part rather than per-item, because the only two cards that read this
 * disagree about what they need and one of them is silent when it is wrong.
 * Emberflame Enlightener ("your units and spells gain {g}powerful") is
 * item-wide; Envoy of Lightning ("your spell effects with a single target are
 * {g}Electric") counts targets, and a composite spell's parts do not all have
 * the same number of them.
 *
 * `targets` is the DECLARED count — how many target slots this part was cast
 * with — NOT how many of them are still alive at resolution. RAQ "[Solved]
 * Envoy of Lightning vs Twin Flame.", in full:
 *
 *   Q: "If Twin Flame is played with only 1 target, is it Electric thanks to
 *       Envoy?"                                    A: "Yes, it will be Electric"
 *   Q: "What if Twin Flame was played targeting two units, but one of them was
 *       removed before Twin Flame resolves. Will it be Electric?"
 *   A: "No, it still has 2 targets, but one of them is invalid (but could
 *       become valid thanks to Gravitational Correction or Warder)."
 *
 * `E.resolveParts` filters dead refs out before it builds `EffectCtx.targets`,
 * so the survivor count is the WRONG number here and gives the wrong answer
 * silently — a two-target Twin Flame that lost a target would come out
 * Electric. The count therefore comes off `part.targets`, the declared list.
 */
export interface EffectAttrCtx {
  /** the resolving item's controller — "YOUR spells" */
  seat: Seat;
  /** the region the item is resolving in (R12) */
  region: number;
  /** what kind of stack item this is; see `isSpellEffect` */
  kind: 'unit' | 'spell' | 'spellUnit' | 'spellToken' | 'virus' | 'triggered' | 'activated' | 'ambush';
  /** the printed card behind it, when there is one (a label-only item — a
   * granted trigger, a bare effect — has none) */
  card?: CardDef;
  /** DECLARED target slots on THIS part (see above: not survivors) */
  targets: number;
}

/**
 * R94: a continuous ATTRIBUTE modifier on a resolving EFFECT — the write side
 * of the channel R79 built the read side of ("[Augment] Your units and spells
 * gain {g}powerful", Emberflame Enlightener; "[Augment] Your spell effects
 * with a single target are {g}Electric", Envoy of Lightning).
 *
 * A sibling of `CostMod`, deliberately NOT an extension of `StaticMod`:
 * `StaticMod.affects` is typed over an `Entity` and a `StackItem` is not one.
 * It radiates by the same rules as both — from a unit in play or from an
 * augment mod anchored on its HOST, scoped to the holder's region (R12) — and
 * ownership lives in the card's own `affects`, not in the gatherer, which is
 * the division `StaticMod` already uses.
 *
 * The designer scales a unit-sourced NONCOMBAT effect by a GRANTED {Powerful}
 * (RAQ "[Solved] Resonant, Combat Damage, Conduit and Powerful": "2/4 Resonant
 * Powerful would deal 4 combat damage to enemy unit and then put effect on
 * stack to deal 8 damage to enemy face"), which is exactly the Emberflame
 * case, so the grants land in `EffectCtx.grantedAttrs` beside R79's virus
 * grants and everything downstream reads one unioned set.
 *
 * Like `CostMod`, `affects` must not re-enter effect-attribute evaluation;
 * read raw state instead.
 */
export interface EffectAttrMod {
  affects: (g: E, self: Entity, ctx: EffectAttrCtx) => boolean;
  attrs: Attr[];
}

/**
 * ⚠ THE OPEN QUESTION, IN ONE PLACE ON PURPOSE (R94): does "your SPELLS"
 * include your spell TOKENS?
 *
 * It is the difference between an Emberflame deck doubling its Burst Fireballs
 * and not, so it is a real deck-construction question and it is NOT settled.
 * The engine's default here is YES, on the plainest reading: a spell token is
 * a spell, and Emberflame's text has no play verb in it to hang a carve-out
 * on. R59 DID carve tokens out of `costMods` — "a spell token is cast from
 * play, not played" — but that carve-out exists because Tranquility says
 * "cards cost [one] more to PLAY", and it does not generalise to a text that
 * only says "your spells".
 *
 * The corpus is thin and second-hand: lordofkaranda, in rules-questions,
 * "Spell tokens are spells and activating them is playing them" — a player,
 * not Caleb, and its second half contradicts R59's basis for the cost layer.
 * Nothing from the designer either way.
 *
 * So: one helper, one edit. If the owner rules the other way, delete
 * `'spellToken'` from this line and both cards change together.
 */
export function isSpellEffect(kind: EffectAttrCtx['kind']): boolean {
  return kind === 'spell' || kind === 'spellUnit' || kind === 'spellToken';
}

/** R95: what a `ModPermission` is being asked about — one attempt to apply one
 * card as a mod. `from` is in the signature ON PURPOSE rather than being
 * hardcoded at the call site: Rook prints "from hand and bin", so it is the
 * CARD that refuses the cache, and the next card to want this can widen or
 * narrow the zone list without touching apply.ts.
 *
 * "MOD" HERE MEANS AUGMENT *AND* GRAFT (R37's word for both), which is why
 * `kind` is on the ctx: `augmentInBattle` is only ever asked about an augment
 * (a graft during battle is a separate rules question nobody has asked), but
 * `applyAtHaste` is asked about both, because Slurpr prints "other MODS". A
 * card that wants only one of the two checks `ctx.kind`. */
export interface ModCtx {
  /** the player trying to apply the mod */
  seat: Seat;
  /** the mod being applied */
  card: CardDef;
  /** the zone it would leave */
  from: 'hand' | 'bin' | 'cache';
  /** the region the application happens in (R12) */
  region: number;
  /** which application this is (R37: a "mod" is an augment or a graft).
   * Optional so the R95 battle-augment call sites, which are augments by
   * construction, need not restate it. */
  kind?: 'augment' | 'graft';
}

/**
 * R95: a continuous PERMISSION to apply a mod where the rules would otherwise
 * refuse — "[Augment] You may augment cards from hand and bin during battle as
 * if they were [Virus]" (Rook).
 *
 * OPT-IN PER CARD, never a general widening, and the designer is explicit that
 * this is the shape. rules-questions, on whether an ordinary card grants it:
 *   chatt_nooga: "Does Steward of the Plain let me apply a virus from my
 *                 discard during combat?"
 *   calebgannon: "That's a very interesting question" / "It shouldn't" /
 *                "But I can see why it might be interpreted that way"
 *   chatt_nooga: "Okay but hear me out: What if it did? Would that be broken?"
 *   calebgannon: "Not really I don't think. If it said 'as if it was in your
 *                 hand' then it could work" → `$card rook` → "Does do that" /
 *                "Steward and rook are good friends"
 * So the default is NO, it takes explicit wording, and Rook is the card with
 * the wording.
 *
 * Structurally a `CostMod` — same ctx shape, same `anchored()` radiation from
 * a unit in play or an augment mod reading from its HOST, same R12 region
 * scoping, same purity rule — but folded as an OR rather than summed, which is
 * exactly why it cannot BE a CostMod: one grantor is enough, and two Rooks are
 * not twice as permissive. `self` is the ANCHOR, which makes Rook's own
 * [Augment] half free: augmented onto a host, the permission belongs to the
 * host's controller.
 *
 * Region scoping is not a convenience, it is the rule. rodanaw in
 * rules-questions, on this very card: "I am 99% sure that Rook has to be in the
 * region, since there are no global effects in Algomancy" — and the general
 * form, elsewhere in the same corpus: "Yes. as with 99.99% of all questions
 * regarding regions."
 */
export interface ModPermission {
  /** may `ctx.seat` apply this card as an AUGMENT during battle? */
  augmentInBattle?: (g: E, self: Entity, ctx: ModCtx) => boolean;
  /**
   * May `ctx.seat` apply this card as a MOD during the R18 haste step —
   * "[Augment] You can apply other mods during [Haste] as if it was
   * deployment" (Slurpr)?
   *
   * The MOD-timing twin of R97's `playAtHaste`, and deliberately R95's shape
   * rather than R97's: an OR-FOLD with no per-turn budget, because Slurpr
   * prints no "each turn" the way Dispatch Courier does. Two Slurprs are not
   * two mods' worth of permission, so nothing has to be counted and no
   * GameState field is needed — `hastePlaysUsed` has no sibling here.
   *
   * "As if it was deployment" is the whole grant: the answer is a boolean, and
   * the deployment branch of `doAugment` / `doGraft` then runs UNCHANGED with
   * only its phase test replaced. Everything deployment already refuses —
   * paying for the mod (R37/R59's `purpose: 'mod'`), the host being in your
   * own region, a graft needing a graft cause on the host — still refuses.
   *
   * ⚠ Asked about AUGMENTS AND GRAFTS alike (`ctx.kind`), because "mod" is
   * R37's word for both. Slurpr checks neither: it grants both halves.
   */
  applyAtHaste?: (g: E, self: Entity, ctx: ModCtx) => boolean;
}

/**
 * R97: what a `PlayPermission` is being asked about — one attempt to PLAY one
 * card at a timing its printed line does not allow.
 *
 * Deliberately the twin of R95's `ModCtx`, field for field, because the two
 * questions are the same question about different verbs: applying a mod is not
 * playing a card (R37), so they must stay two seams, but a card that wants to
 * widen one usually wants to phrase it the same way as a card that widens the
 * other. `from` is in the signature for exactly R95's reason — the printed zone
 * list belongs to the granting CARD, not to the rules.
 */
export interface PlayCtx {
  /** the player trying to play the card */
  seat: Seat;
  /** the card being played */
  card: CardDef;
  /** the zone it would leave */
  from: 'hand' | 'bin' | 'cache';
  /** the region the play happens in (R12) */
  region: number;
  /** R97: how many grant-funded haste-step plays `seat` has ALREADY made this
   * turn. The printed budget is per-card prose ("Each turn, you may play a
   * unit…"), so the card spends it, not the engine: Dispatch Courier returns
   * an allowance of 1 and the engine compares the sum of allowances with this.
   * A grantor with no budget in its text simply ignores the field. */
  usedThisTurn: number;
}

/**
 * R97: a continuous PERMISSION to PLAY a card at a timing the printed line
 * refuses — "[Augment] Each turn, you may play a unit during the mana step as
 * if it had [Haste]" (Dispatch Courier).
 *
 * The rules half is settled and is not this seam's to decide. Caleb's Discord,
 * rules-questions: "that symbol is haste, meaning you can play it during the
 * mana step" and "There is no priority during the mana step, but you can play
 * haste cards and resources as special actions"; asked what the mana step IS,
 * nyarlathotep8457: "Yes the Mana step is the resources step of the planning
 * phase." So the printed "mana step" is this engine's R18 haste step, and
 * Courier is asking for exactly one thing: a seat-level play-timing grant.
 *
 * Radiation is R95's, unchanged: the `anchored()` walk (a unit in play, or an
 * augment mod read from its HOST), R12 region scope, the shallow R62 guard,
 * a reentrancy latch. What is NOT R95's is the FOLD — this one SUMS, because
 * the printed text carries a per-turn quantity. Two Rooks are not twice as
 * permissive (a boolean OR); two Couriers each print "Each turn, you may play
 * a unit", and two of them are two plays. `Infinity` is the OR-fold's
 * behaviour for a grant with no budget in its text, so both shapes fit one
 * number.
 *
 * ⚠ WHAT THE GRANT CANNOT DO, and it is a ruling, not an omission: a {Battle}
 * card stays a battle card. RAQ "[Solved] Dispatch Courier vs Battle Timing",
 * in full — Q: "Does units / spell-units with :battle: timing can be played
 * during :haste: thanks to Dispatch Courier?" A: "No, despite gaining :haste:
 * they can still only be played during :battle:." The designer's own reasoning,
 * in rules-questions on this exact case: calebgannon "it's gotta be no" /
 * "battle cards are designed to be played in battle only. Not all of them will
 * cause problems but I think some will". That refusal is GENERAL — it is about
 * what gaining haste can do, not about Courier — so it lives in the engine
 * gate (`E.hastePlayAllowance`), above every grantor, rather than in any one
 * card's predicate.
 */
export interface PlayPermission {
  /** R97: how many times per turn may `ctx.seat` play this card during the
   * HASTE step (R18) despite its printed timing? Return 0 for no (the
   * default), a finite count for a printed "each turn" budget, or `Infinity`
   * for an unbudgeted grant. The engine sums every grantor's answer and
   * compares the total with `ctx.usedThisTurn`. */
  playAtHaste?: (g: E, self: Entity, ctx: PlayCtx) => number;
}

/**
 * R104: what an `AmountMod` is being asked about — ONE quantity, on its way
 * through the engine, before anything has committed it.
 *
 * The seven cards ledger #60 lists split cleanly into two families, and this
 * is the first: text that changes a NUMBER without changing what happens.
 * "It deals that much damage plus 1 instead" (Conduit of Pain), "put that many
 * counters plus one instead" (Flux Resonator, Proliferating Slime). Nothing is
 * substituted, nothing is redirected — the quantity is simply different by the
 * time it lands.
 *
 * `kind` names the quantity, and the list is CLOSED on purpose (the same
 * narrowness `replaceRotDamage`'s comment argues for): a new replaceable
 * quantity gets a new member here and a new consult site in the engine, so
 * every one of them is greppable. There is no "any event" form.
 */
export interface AmountCtx {
  /** which quantity is passing through */
  kind: 'counters' | 'effectDamage' | 'rot' | 'debt';
  /**
   * the region it happens in (R12) — a mod only sees its own region.
   *
   * UNDEFINED means the change is not tied to a region and every holder is
   * asked, which is not a loophole but `E.fireEvent`'s own rule reused: it
   * scopes listeners to `ev.data.region` and, when an event carries none,
   * dispatches to all of them. Rot and debt outside a battle are exactly that
   * event — `gainRot` writes no region when `s.battle` is null — so a modifier
   * that used to be a `rotGained` trigger must be asked in the same places or
   * the card quietly narrows.
   */
  region?: number;
  /**
   * the amount as it stands, SIGNED. Counters are signed (+1/+1 vs -1/-1), so
   * "one more of the same thing" is `amount > 0 ? +1 : -1` and not `+1`.
   * Already past any engine scaling that happens earlier — {Powerful} has
   * doubled `effectDamage` by the time this is asked (see R104's order note).
   */
  amount: number;
  /** the unit receiving it, when the recipient is a unit */
  unit?: Entity;
  /** the player receiving it, when the recipient is a player (rot, debt, a
   *  face hit) */
  player?: Seat;
  /** the controller of whatever is doing it — "an ALLIED source" is
   *  `sourceSeat === self.controller` */
  sourceSeat?: Seat;
  /** the source card's name, for the log */
  sourceName?: string;
  /** combat damage, or an effect's. Always false today: the only `kind` that
   *  can be combat is damage, and combat damage has its own two hooks. */
  combat: boolean;
}

/**
 * R104: a continuous AMOUNT modifier. `delta` returns how much to ADD.
 *
 * SUMMED, not first-true-consumes, and that is a ruling rather than a
 * convenience. Caleb, on how replacements of this shape compose:
 *
 *   "a replacement only happens once … The replacement just takes what would
 *    be 1 and makes it 2"
 *
 * So two DIFFERENT modifiers both apply (two Conduits of Pain make a 1 into a
 * 3), and none applies to its own contribution — which falls out of the shape
 * rather than needing a guard: an `AmountMod` is CONSULTED, once, as a pure
 * query, where the old trigger implementations RE-ENTERED `addCounters` and
 * needed module-level `let` flags to stop themselves looping. Deleting those
 * flags is the point (report #60: "Five module-level mutable flags exist
 * purely to paper over this").
 *
 * Modelled on `CostMod` line for line — the same `anchored()` walk, the same
 * R12 region scope, the same shallow R62 suppression guard, the same
 * reentrancy latch, the same "ownership lives in the card's own predicate, not
 * in the gatherer". Like `CostMod`, `delta` must not call anything that
 * re-enters amount evaluation; read raw state instead.
 */
export interface AmountMod {
  delta: (g: E, self: Entity, ctx: AmountCtx) => number;
}

/**
 * R104: ONE token about to be created, as a request the replacement layer can
 * substitute before anything exists.
 *
 * `form` is the physical difference between the two creation primitives —
 * `E.spawnUnit(…, { token: true })` puts a unit token on the board,
 * `E.createSpellToken` puts a spell token in the region — and Cosmic
 * Conspirator's four named types straddle it ("a Robot, Poison, Crystal or
 * Fireball"), which is why a request carries the form rather than the caller
 * deciding it.
 *
 * `x` is deliberately ONE field for two things: a spell token's X, and a unit
 * token's spawn counters (Robot X is "I spawn with X +1/+1 counters on me").
 * The Conspirator's reminder text — "(With the same X value.)" — is what makes
 * that the right shape: the number survives the swap in either direction.
 */
export interface TokenRequest {
  form: 'unit' | 'spell';
  name: CardName;
  /** a spell token's X, or a unit token's spawn counters */
  x: number;
  seat: Seat;
  region: number;
}

export interface CardBehavior {
  /** X-cost cards only: the smallest legal X ("X can't be zero" → 1).
   * Casting requires (and X options start at) this much open mana. */
  xMin?: number;
  abilities?: Ability[];
  /** continuous stat/attr projections while this card is a unit in play OR
   * an augment mod (text-box [Augment] statics transfer with the card) */
  statics?: StaticMod[];
  /** R118: continuous FACE projections — "I have all abilities of adjacent
   * allies" (Ancient One). Same radiation rules as `statics` again. */
  projects?: FaceProjection[];
  /** R59: continuous COST modifiers, same radiation rules as `statics`
   * ("Spells cost [one] more to play during battle" — Tranquility) */
  costMods?: CostMod[];
  /** R94: continuous ATTRIBUTE grants onto resolving EFFECTS, same radiation
   * rules as `statics` and `costMods` ("[Augment] Your units and spells gain
   * {g}powerful" — Emberflame Enlightener) */
  effectAttrs?: EffectAttrMod[];
  /** R95: continuous PERMISSIONS to apply a mod where the rules otherwise
   * refuse, same radiation rules again ("[Augment] You may augment cards from
   * hand and bin during battle as if they were [Virus]" — Rook) */
  modPermissions?: ModPermission[];
  /** R97: continuous PERMISSIONS to PLAY a card at a timing its printed line
   * refuses, same radiation rules again — but SUMMED rather than OR-folded,
   * because the printed text carries a per-turn count ("[Augment] Each turn,
   * you may play a unit during the mana step as if it had [Haste]" — Dispatch
   * Courier) */
  playPermissions?: PlayPermission[];
  /** the card can be applied as an augment even without augmentAttrs or
   * augmentText — its [Augment] text is implemented via `statics` */
  augmentable?: boolean;
  /** R64: "I must be targeted if able" (Gatekeeper of Souls) — a targeting
   * restriction that narrows OTHER effects' candidate lists rather than its
   * own. Radiates like a static: live while the card is a unit in play, and
   * donated while it is an augment mod. */
  mustBeTargeted?: boolean;
  /** R42: this card may be prophesied out of its owner's BIN as well as their
   * hand ("I can be prophesied from your bin" — Angel of Anguish). No card may
   * be prophesied from the bin unless it says so, so this defaults to false
   * and the `prophesy` action's `from: 'bin'` is refused without it. */
  prophesyFromBin?: boolean;
  /**
   * R100: "I can't be played from your hand." (Calming Force) — the mirror of
   * `prophesyFromBin` and defaulting the other way: every card may be played
   * from hand unless it says it may not, so this is opt-in and permissive by
   * default.
   *
   * A NEW flag rather than a reuse, because nothing existing means this. R64's
   * `restrict` narrows what an EFFECT may TARGET; `prophesyFromBin` is about a
   * different zone and a different verb; `timing` is about WHEN, not WHERE FROM.
   * The engine was strictly more permissive than the printed card, and this is
   * the whole of the difference.
   *
   * ⚠ It restricts PLAYING FROM HAND and nothing else. The card is still
   * reachable — cached and released (R42/R45), played from a bin under a
   * permission (R96), applied as a mod, discarded, recycled — because the
   * printed line names one zone and one verb. Enforced in `doPlayCard` and
   * refused by all three `legalActions` sites that push a hand `playCard`: a
   * refusal the UI still offers as a legal click is its own playtest report.
   */
  noPlayFromHand?: boolean;
  /** R29: "You may play me into an open spot in your formation" (Tiderunner
   * Initiate; Trench Stalker's first clause). The card is PLAYED into the
   * line — the spot is chosen in the cast window like any other part of how a
   * card is played, and the unit is written into the column atomically with
   * its own spawn, so it is never observable standing outside the formation.
   * Distinct from R75's `E.placeInFormation`, which is for an EFFECT that
   * creates a unit in a formation and rightly places at resolution. */
  playsIntoFormation?: boolean;
  /** effect of a spell / spell unit / spell token when played */
  spellEffect?: EffectDef;
  /** the [Switch]-marked effect that transfers when this card is grafted */
  graftEffect?: { bounded: boolean; effect: EffectDef };
  /** text-box [Augment] abilities that transfer when this card augments */
  augmentText?: Ability[];
  /** R38 replacement effect: rot is about to deal `amount` damage to `seat`.
   * Return true to REPLACE the damage (do whatever the card does instead —
   * Skittering Blight: "instead put that many +1/+1 counters on me"), false to
   * let it through. Called from E.rotDamage() at the start of deployment,
   * before the damage event exists. `self` is the unit the text is anchored on
   * — the card itself when it is a unit in play, or the HOST when the text
   * arrives via an augment mod (Skittering Blight prints it under [Augment];
   * same anchoring rule as StaticMod). Deliberately a one-off hook, not a
   * replacement framework: rot damage is the only replaceable event in the
   * engine (see E.replaceRotDamage). */
  replaceRotDamage?: (g: E, self: Entity, seat: Seat, amount: number) => boolean;
  /** R38 replacement effect, the second and last one: a COLUMN is about to
   * deal `amount` combat damage to `seat`. Return true to REPLACE the damage
   * (Blightsea Polyp: "[Augment] Columns deal combat damage to players as 1
   * rot" — the card gains the victim 1 rot and returns true), false to let it
   * through. Asked once PER COLUMN, which is why the reminder text's "a column
   * of a 4/4 and a 2/2 would give the opponent 1 rot" holds whatever the
   * column's power is.
   *
   * ⚠ Replacing the damage does NOT unmake it: Caleb ruled (2024-10-24) the
   * damage still counts as having been DEALT, so {Lethal} still kills through
   * it, {Thieving} still draws, and {Blessed} still gains. Only the life total
   * is spared.
   *
   * Anchored like replaceRotDamage (a mod's hook reads from its HOST), but NOT
   * restricted to one seat's cards: the printed text says "columns", plural
   * and unowned, so every holder in play is offered the replacement and the
   * card itself decides whose columns it cares about. */
  replaceCombatDamageToPlayer?: (g: E, self: Entity, seat: Seat, amount: number,
    info: {
      attacker: Seat; region: number;
      /** R98: the striking COLUMN's live attributes — {Piercing}, {Lethal},
       * {Thieving}, {Powerful}, … Added because a hook that has to tell a
       * Piercing hit from a plain unblocked one could not: Oorblak's parked
       * half turns entirely on that distinction (RAQ "[Solved] Oorblak vs
       * Piercing"). */
      attrs: Set<string>;
      /** R98/R61 {Pure}: the exchange was attribute-blind, so `attrs` is empty
       * and the card should behave as if the column printed nothing. */
      pure: boolean;
    }) => boolean | number;
  /**
   * R104: continuous AMOUNT modifiers — "it deals that much damage plus 1
   * instead", "put that many counters plus one instead". Same radiation rules
   * as `statics`/`costMods` (a unit in play, or an augment mod reading from
   * its HOST, scoped to the anchor's region), and SUMMED like `costMods`
   * rather than first-true-consumes like the `replaceX` hooks below. See
   * `AmountMod` for why the two families compose differently.
   */
  amountMods?: AmountMod[];
  /**
   * Replacement: `seat` is about to take their turn's CARD STEP — the draft
   * step in mode 'draft' (look at your pack, merge, leave 10), the draw phase
   * in mode 'constructed' (draw 4, put 2 back). Return true to REPLACE it: the
   * normal step does not happen at all and the hook does whatever the card
   * does instead. First true consumes, like the other replacements, so two
   * copies replace the step once.
   *
   * Worldbender is the pool's only one, and it is the reason the hook takes
   * the MODE into account rather than being "skip and draw one": what the step
   * hands you differs per format, so what replaces it does too (report #87 —
   * draft: draw 1 on top of the turn's 2, no life; constructed: draw 3, since
   * constructed folds the turn draw into the draw phase, and lose 3 life).
   *
   * Anchored like the other replacement hooks (units in play plus augment mods
   * reading from their host) but scoped by CONTROLLER, not region: a card step
   * belongs to a seat, and at the top of a turn there is no battle to scope
   * to. `self` is the anchor; `seat` is its controller, passed explicitly
   * because that is what the step belongs to.
   *
   * Consulted only where a card step exists. Mode 'shared' has none — its
   * whole turn draw is startTurn's flat 2 — so a card declaring this is inert
   * there. OPEN: whether that is what 'shared' should do.
   */
  replaceCardStep?: (g: E, self: Entity, seat: Seat) => boolean;
  /**
   * R104 replacement: `seat` is about to gain `amount` life. Return true to
   * REPLACE the gain — the hook does whatever the card does instead
   * (Nullbringer: "they lose that much life instead" → `g.loseLife(seat, n)`)
   * — false to let it through. First true consumes; the gain never happens, so
   * NO `lifeGained` event is fired and nothing that watches life gain hears
   * about a gain that did not occur.
   *
   * Anchored exactly like `replaceRotDamage` (units in play plus augment mods
   * reading from their HOST), but NOT seat-scoped: Nullbringer prints "if A
   * PLAYER would gain life", unowned, so every holder in the region is offered
   * the replacement and the card decides whose gains it cares about.
   */
  replaceLifeGain?: (g: E, self: Entity, seat: Seat, amount: number, why: string) => boolean;
  /**
   * R104 replacement: `n` counters are about to be put on `target`. Return the
   * entity they should be put on INSTEAD (Counter Theif: "those counters are
   * placed on me instead" → the anchor), or null to decline. First non-null
   * consumes; the counters land on exactly one unit either way, so this is a
   * REDIRECT and never a multiplier.
   *
   * `n` is already post-`AmountMod` — a Flux Resonator's "plus one" is part of
   * what would be placed, so it is part of what gets stolen.
   */
  replaceCounters?: (g: E, self: Entity, target: Entity, n: number) => Entity | null;
  /**
   * R104 replacement: one token is about to be created. Return a substituted
   * request (Cosmic Conspirator: "you may instead create a token of any of
   * these types"), or null to decline. First non-null consumes.
   *
   * Consulted BEFORE anything is created — that is the whole point, and it is
   * playtest report #64: the old trigger really created the Robot, fired a
   * `spawned` for it and then erased it, so the swap was visible on the board
   * and audible in the event stream. A hook that runs first makes the printed
   * token the only one that ever exists.
   *
   * The hook MAY raise a decision (`E.askInResolution`), because "you may" is
   * a choice inside the replacement rather than a triggered ability.
   */
  replaceTokenCreation?: (g: E, self: Entity, req: TokenRequest) => TokenRequest | null;
  /**
   * R104 replacement, the BATCH form: one effect has finished creating tokens
   * and `batch` is everything it created, in creation order. Return extra
   * tokens to create alongside them (Automaton of Abundance: "instead create
   * those tokens plus an additional copy of each unique token you created"),
   * or null to decline. First non-null consumes.
   *
   * A BATCH and not a per-token hook because the printed word is "each UNIQUE
   * token", and uniqueness is a property of the whole creation, not of one
   * spawn — report #60: "Automaton of Abundance fires per spawn so N identical
   * tokens yield N copies instead of one per unique". The batch is one
   * resolution of one effect part, the same unit R80 gave effect damage.
   */
  replaceTokenBatch?: (g: E, self: Entity, batch: readonly TokenRequest[]) => TokenRequest[] | null;
  /** UI-only PURE query (playtest #5): the amount a state-derived X spell
   * (e.g. Burning Vengeance's "units that died this battle") would use if it
   * resolved RIGHT NOW for `seat`, with `region` the active battle region.
   * Never called by the engine, apply(), or any replay-affecting path — the
   * client shows it as an "X = N right now" badge on hand cards during
   * battle. null = no meaningful number right now. */
  xPreview?: (g: E, seat: Seat, region: number) => number | null;
  /** UI-only PURE query, the SAME contract as `xPreview` above — never called
   * by the engine, apply(), or any replay-affecting path.
   *
   * Report #85: "Soul Siphon (and cards like it) should have a way of showing,
   * while in your hand, what the X value is for each player." `xPreview`
   * cannot: it returns ONE number keyed on the hand owner's seat, and Soul
   * Siphon's X is "the life TARGET PLAYER lost in this battle" — one value per
   * player, not one value. So this is a LIST of labelled rows.
   *
   * It is the hook for any card reading a battle counter the board does not
   * print: life lost/gained, spells played, cards trashed, ally deaths. Those
   * ledgers are all PUBLIC (every one is bumped by a visible event, and
   * counters can only move during battle, which has no hidden simultaneous
   * segment — server/rooms.ts segmentKey() returns null for it), so showing
   * BOTH seats leaks nothing.
   *
   * Label with 'you' for `seat` and the opponent's name — `perSeatRows` in
   * sets/helpers.ts does exactly that. A card whose number does NOT differ by
   * player returns a single row naming what it counts. null = nothing to say.
   *
   * A card may define this, `xPreview`, or neither; a card that defines both
   * has these rows preferred, and the two must agree. */
  xPreviewRows?: (g: E, seat: Seat, region: number) => XPreviewRow[] | null;
}

/** one labelled line of a card's live X preview (#85) */
export interface XPreviewRow { label: string; x: number }

export type CardDef = Printed & CardBehavior;

const REGISTRY = new Map<string, CardDef>();
const PRINTED = printedJson as Record<string, Printed>;

export function card(name: string, behavior: CardBehavior): void {
  const printed = PRINTED[name];
  if (!printed) throw new Error(`No printed data for "${name}" — add it to scripts/extract-printed.mjs POOL`);
  // a second card() for the same name would silently REPLACE the first — and
  // since Map.set keeps insertion order, even DECK_LIST would not shift, so
  // nothing downstream could ever notice. Fail loudly instead.
  // (registerSynthetic stays permissive: test files redefine test cards.)
  if (REGISTRY.has(name)) throw new Error(`"${name}" is already registered — duplicate card() call`);
  REGISTRY.set(name, { ...printed, ...behavior });
  ZONE_INDEX = null;   // R51: a new registration may add a zone trigger
}

/** Register a card that is not in the oracle pool (unit tokens, test cards). */
export function registerSynthetic(printed: Printed, behavior: CardBehavior): void {
  REGISTRY.set(printed.name, { ...printed, ...behavior });
  ZONE_INDEX = null;
}

/**
 * R71: a second printed NAME for one registered card. The Wraith token is the
 * only case: the token was renamed FROM "Wight" TO "Wraith", and the printed
 * data is mid-transition in the other direction — six cards already read
 * "Wraith" while `Blight's End` still carries the OLD name ("Augment a Wight
 * onto X target units"). Both must resolve to ONE card, so the current name
 * `Wraith` is canonical and the retired `Wight` is its alias.
 *
 * Aliases resolve in getCard() only; they are deliberately NOT in
 * allCardNames(), so nothing downstream (DECK_LIST, the draft pool, the card
 * browser) can ever see the two names as two things. State always stores the
 * canonical name — the alias exists for lookups, never for storage.
 */
const ALIASES = new Map<string, string>();
export function registerAlias(alias: string, target: string): void {
  ALIASES.set(alias, target);
}
/** the registered name `name` refers to (itself, unless it is an alias) */
export function canonicalCardName(name: string): string {
  return ALIASES.get(name) ?? name;
}

export function getCard(name: string): CardDef {
  const def = REGISTRY.get(name) ?? REGISTRY.get(canonicalCardName(name));
  if (!def) throw new Error(`Unknown card "${name}"`);
  return def;
}

export function allCardNames(): string[] {
  return [...REGISTRY.keys()];
}

/** Look up the EffectDef a serialized effect key refers to. */
export function effectByKey(key: string): EffectDef {
  const [tag, rest] = [key.slice(0, key.indexOf(':')), key.slice(key.indexOf(':') + 1)];
  if (tag === 'spell') {
    const def = getCard(rest).spellEffect;
    if (!def) throw new Error(`${rest} has no spell effect`);
    return def;
  }
  const [name, idxStr] = rest.split('#');
  const idx = Number(idxStr);
  if (tag === 'ability') {
    const ab = getCard(name!).abilities?.[idx];
    if (!ab) throw new Error(`${name} has no ability #${idx}`);
    return ab.effect;
  }
  if (tag === 'graft') {
    const def = getCard(rest).graftEffect;
    if (!def) throw new Error(`${rest} has no graft effect`);
    return def.effect;
  }
  if (tag === 'augment') {
    const ab = getCard(name!).augmentText?.[idx];
    if (!ab) throw new Error(`${name} has no augment text #${idx}`);
    return ab.effect;
  }
  if (tag === 'ambush') return ambushEffect(rest);
  throw new Error(`Bad effect key "${key}"`);
}

/** The Ambush play mode's effect, shared by every ambush card (Manual p.40):
 * "Recall target ally, put me into their position in play." Target gone at
 * resolution → the item fizzles and the ambusher is binned (card ruling). */
const AMBUSH_EFFECTS = new Map<string, EffectDef>();
export function ambushEffect(name: CardName): EffectDef {
  let def = AMBUSH_EFFECTS.get(name);
  if (!def) {
    def = {
      targets: { what: 'allyUnit', prompt: `${name}: recall target ally — the ambusher takes their position` },
      run: (g, ctx) => {
        const t = ctx.targets[0];
        if (t && 'id' in (t as object)) g.ambushSwap(t as Entity, name, ctx.controller);
      },
    };
    AMBUSH_EFFECTS.set(name, def);
  }
  return def;
}

/** affinity pips of a cost string, e.g. "rr" -> { fire: 2 } */
export const ELEMENT_OF_PIP: Record<string, string> = {
  r: 'fire', b: 'water', e: 'earth', g: 'wood', m: 'metal', l: 'light', d: 'dark',
};
export function affinityPips(cost: string): Record<string, number> {
  const pips: Record<string, number> = {};
  for (const ch of cost) {
    const el = ELEMENT_OF_PIP[ch];
    if (el) pips[el] = (pips[el] ?? 0) + 1;
  }
  return pips;
}

/**
 * R51: index of the zone-resident triggers in the pool, keyed by event type.
 * fireEvent() consults it on EVERY event, so it must be a map lookup and not
 * a scan: built once, lazily (the registry fills as the batch modules import),
 * and invalidated by card()/registerSynthetic() so a late registration is
 * still seen. An event type nobody listens for costs one failed Map.get().
 */
export interface ZoneTrigger { card: string; abilityIndex: number; zone: 'bin' | 'cache' }
let ZONE_INDEX: Map<EventType, ZoneTrigger[]> | null = null;
function buildZoneIndex(): Map<EventType, ZoneTrigger[]> {
  const idx = new Map<EventType, ZoneTrigger[]>();
  for (const [name, def] of REGISTRY) {
    (def.abilities ?? []).forEach((ab, abilityIndex) => {
      if (ab.type !== 'triggered' || !ab.zone) return;
      for (const type of ab.events) {
        const list = idx.get(type) ?? [];
        list.push({ card: name, abilityIndex, zone: ab.zone });
        idx.set(type, list);
      }
    });
  }
  return idx;
}
export function zoneTriggersFor(type: EventType): ZoneTrigger[] {
  ZONE_INDEX ??= buildZoneIndex();
  return ZONE_INDEX.get(type) ?? [];
}

export function isTriggered(a: Ability): a is TriggeredAbility { return a.type === 'triggered'; }

/** A card can be grafted onto a host iff it has a [Switch]-marked effect. */
export function isGraftable(name: string): boolean {
  return !!getCard(name).graftEffect;
}

/** A host can receive grafts iff it has its own graft cause (Manual p.33). */
export function graftCauseIndex(name: string): number {
  const abilities = getCard(name).abilities ?? [];
  return abilities.findIndex(a => a.graftCause);
}

/** A card can augment iff it grants type-line attrs or has [Augment] text. */
export function isAugment(name: string): boolean {
  const def = getCard(name);
  return def.augmentAttrs.length > 0 || (def.augmentText?.length ?? 0) > 0 || !!def.augmentable;
}
