/* Card definition DSL (docs/04 §5): declarative defs over effect primitives.
 *
 * Printed data comes from printed.json (generated by scripts/extract-printed.mjs
 * from AlgomancyCards-OracleText.json — never hand-copied). Only behavior is
 * authored here.
 *
 * Effects are code, but stack items must be serializable state — so a stack
 * item references its effects by string keys resolved through the registry:
 *   spell:<Card>       the card's spell effect
 *   ability:<Card>#<i> the effect of abilities[i]
 *   graft:<Card>       the card's [Switch]-marked transferable effect
 *   augment:<Card>#<i> the effect of augmentText[i] (text-box [Augment] text)
 */
import type {
  Attr, CardName, EngineEvent, Entity, EventType, Seat, TargetRef,
} from '../types.ts';
import type { E } from '../engine.ts';
import printedJson from './printed.json' with { type: 'json' };

export interface Printed {
  name: string;
  /** element factions ("fire"; two for hybrids; [] / absent for synthetics) */
  factions?: string[];
  cost: string;                     // affinity pips, e.g. "rr"
  mana: number | 'X';
  power: number;
  toughness: number;
  type: string;
  kind: 'unit' | 'spell' | 'spellUnit' | 'spellToken';
  timing: 'deploy' | 'battle' | 'haste';
  attrs: Attr[];
  virus: boolean;
  burst: boolean;
  augmentAttrs: Attr[];             // type-line [Augment] grants (mods.py rule)
  /** "[Battle] Ambush [4bb]" alternative play mode: mana + affinity pips */
  ambush?: { cost: string; mana: number };
  /** Light & Dark: the printed "[2] Prophecy — Two Turns Pass" banner beneath
   * the title — an alternative cost + the condition that releases it. Stripped
   * out of `text` by the extractor. A prophecy GRANTED by rules text (e.g.
   * "It gains 'Prophecy — One Turn Passes'") is not a printed banner. */
  prophecy?: { mana: number; condition: string };
  /** Light & Dark: a printed "[Gain 4 debt]" bracketed additional cast cost
   * (its own line in the text box). Stripped out of `text`. */
  gainDebt?: number;
  /** R40: the printed "Discard me" cost line — an alternative play mode like
   * Ambush ("1 Discard me" on Dropslime, "2 [d] Discard Me. {Battle}" on
   * Nothyr): pay this cost, discard the card from hand, and the resulting
   * TRASH fires the card's own "when I am trashed" trigger. `timing` is the
   * timing of THIS MODE when the line carries its own marker — Nothyr's
   * {Battle} sits on the discard-me line while the card itself is a deploy
   * unit. Stripped out of `text` by the extractor. */
  discardMe?: { cost: string; mana: number; timing?: 'battle' };
  text: string;
  image: string;
}

/** A resolved 'cachedCard' target: the entry is looked up by its stable uid at
 * RESOLUTION, so `card` is what is actually sitting there now. Effects act on
 * it through E.cacheIndexOf(seat, uid). */
export interface ResolvedCached { cached: { seat: Seat; uid: number; card: CardName } }

/** Resolved target passed to effect run(): an entity, a player, a stack item
 * id, or a cached card. */
export type ResolvedTarget = Entity | { player: Seat } | { stack: number } | ResolvedCached;

export interface EffectCtx {
  controller: Seat;
  sourceName: string;
  sourceId?: number;
  region: number;
  targets: ResolvedTarget[];
  x?: number;
  /** receipt of this part's cast-time [cost] payment (R35) — e.g. the unit
   * sacrificed to cast, with its stats snapshotted at payment time */
  costPaid?: { sacrificed?: { card: CardName; power: number; defense: number } };
  /** {Modular}: the mods applied to this card as it was played (Spellbind).
   * Their graft effects already ride as extra parts; this is the readable
   * list, for text that wants to know what is attached. */
  mods?: CardName[];
  /** R1: the event snapshot for triggered abilities (conditions were checked at
   * event time; amounts must be computed here, at resolution, from live state) */
  event: EngineEvent | null;
  /** mid-resolution choice (R4 electric path, R6 payments). Returns the stored
   * answer or suspends the engine with a decision. Parts that use this must
   * request all choices before mutating state, or use plan-then-commit —
   * the engine rolls back to the part boundary on suspension. */
  choose: (key: string, dec: { kind: 'payOrDecline' | 'electricPath'; seat: Seat; prompt: string; options: { label: string; value: unknown; card?: CardName }[] }) => unknown;
}

export interface TargetSpec {
  /** 'cachedCard' (R41): a card in EITHER player's cache — the zone is public
   * information, so both are legal targets, and it is not region-scoped.
   * (Prismatic Observer: "Recall up to one target cached card".) */
  /** R60 — "target effect" vs "target SPELL effect". The card set draws the
   * line itself: three cards say "target spell effect" (Dreadwave Devourer,
   * Null Drone, Dream Lapse) and one says "target NONSPELL effect" (Nothyr).
   * Both qualifiers would be dead words if plain "effect" meant only spells,
   * so plain "effect" is the SUPERSET.
   *   'stackSpell'  — spell / spell unit / spell token / ambush. The cards
   *                   that spell out "spell effect".
   *   'stackEffect' — all of the above PLUS triggered and activated abilities
   *                   and viruses: anything on the stack that is an effect.
   *                   The cards that just say "effect".
   * A UNIT on the stack is in neither: a unit arriving in play is not an
   * effect, and it has no parts to negate. */
  what: 'unit' | 'allyUnit' | 'any' | 'stackSpell' | 'stackEffect' | 'cachedCard';
  prompt: string;
  /** maximum number of targets chosen AT CAST TIME (default 1). Distinct
   * targets; the chooser gets a "done" option once `min` are picked. */
  count?: number;
  /** minimum targets before "done" is offered (default 1) */
  min?: number;
  /** R58: per-SLOT restriction for a multi-target spec — `slots[i]` governs
   * target i and falls back to `what`. Fight prints "target ally and ANOTHER
   * target unit": two cast-time targets whose legality differs by slot
   * (['allyUnit', 'unit']). Without this a two-target spec could only ask one
   * question twice, which is how Fight ended up choosing its second target
   * mid-resolution instead. */
  slots?: TargetSpec['what'][];
  /** R58: per-slot prompt, same indexing as `slots`; falls back to `prompt`. */
  slotPrompts?: string[];
}

/** R58: the restriction governing target slot `i` of a spec. */
export function slotWhat(spec: TargetSpec, i: number): TargetSpec['what'] {
  return spec.slots?.[i] ?? spec.what;
}

/** R58: the spec as it applies to slot `i` — what targetCandidates should be
 * asked for when filling that one slot. */
export function specForSlot(spec: TargetSpec, i: number): TargetSpec {
  return { ...spec, what: slotWhat(spec, i) };
}

/**
 * A bracketed additional cost ("[Sacrifice a unit]: …", "[Pay 3 life]",
 * "[Discard a card]", "[Gain 4 debt]") chosen and PAID AT CAST, before the
 * item reaches the stack (R35). An unpayable cost makes the cast ILLEGAL;
 * on a grafted rider it is optional and declining skips that part.
 *
 * `n` is the amount, and means nothing for 'sacrificeUnit' (always one unit).
 * 'payLife' is governed by R49: you may pay N life only while you have MORE
 * than N — a cost you cannot survive is not payable.
 */
export type CastCost =
  | { kind: 'sacrificeUnit' }
  | { kind: 'payLife'; n: number }
  | { kind: 'discardCard'; n: number }
  | { kind: 'gainDebt'; n: number };

export interface EffectDef {
  targets?: TargetSpec;
  /** cast-time additional cost (R35). On a spell: paying is part of casting —
   * with nothing to pay the cast is illegal. On a graft part joining a
   * composite: the carrier's controller pays (or declines — the rider is then
   * skipped) when the composite collects its cast-time decisions, exactly
   * where graft targeting happens. The receipt lands in ctx.costPaid. */
  castCost?: CastCost;
  /** R5: if true, all targets invalid at resolution fizzles the whole effect.
   * Default: resolve partially against remaining legal targets. */
  allOrNothing?: boolean;
  run: (g: E, ctx: EffectCtx) => void;
}

export interface TriggeredAbility {
  type: 'triggered';
  events: EventType[];
  /** only fire when the event's source is this entity */
  self?: boolean;
  /**
   * R51: the trigger listens while the CARD SITS IN THIS ZONE rather than
   * while it is a unit in play ("If I am in your bin, after combat …" —
   * Lurking Dread, Inexorable Miasma, Cinder Scuttler). fireEvent() scans
   * entities in play and a card in a bin is not one, so these are dispatched
   * separately, anchored on a DETACHED stand-in entity with id -1 (exactly
   * like R40's fireOwnTrashTrigger): `self` is not a real unit, it cannot be
   * targeted, it radiates no statics and its bounded budget lives only for
   * the one firing. `when` receives that stand-in with `owner`/`controller`
   * set to the zone's seat, so "if I am in YOUR bin" is ctx.controller.
   *
   * Only ONE copy of the card fires per zone per event even if the zone holds
   * several — the printed cards are all "if I am in your bin", a single
   * standing permission, not a per-copy trigger.
   */
  zone?: 'bin' | 'cache';
  /** R1: condition — evaluated once, at event time */
  when?: (g: E, self: Entity, ev: EngineEvent) => boolean;
  label: string;
  /** [Switch1]: once per turn, tracked per card (R9) */
  bounded?: boolean;
  /** carries a graft symbol => is a graft cause (grafts can attach to it) */
  graftCause?: boolean;
  effect: EffectDef;
}

/**
 * R49: what activating an ability costs. Every one of these GATES the
 * activation — an ability whose cost cannot be paid is not offered by
 * legalActions and is refused by apply() — instead of fizzling at resolution.
 *
 *  - mana / life / debt / sacrificeSelf carry no choice, so doActivateAbility
 *    pays them outright, before the item is built.
 *  - discard / sacrificeOther carry a choice, so they ride on the item as
 *    `pendingCosts` and are chosen in the cast window, still before the item
 *    reaches the stack: no one may respond between cost and effect.
 *
 * `life` obeys R49: payable only while you have MORE life than it costs.
 */
export interface AbilityCost {
  mana?: number;
  sacrificeSelf?: boolean;
  /** "Pay N life:" */
  life?: number;
  /** "Gain N debt:" */
  debt?: number;
  /** "Discard a card:" — N cards from your hand */
  discard?: number;
  /** "Sacrifice a unit:" — N units you control OTHER than the source */
  sacrificeOther?: number;
  /** "Discard a card OR sacrifice a nontoken unit:" — N payments, each of
   * which may be either a hand card or another NONTOKEN unit you control.
   * The one either/or shape the pool actually prints (Pallid Gorger,
   * Combustible Bogwalker, Lilbot); a general cost algebra is not worth it. */
  discardOrSacrifice?: number;
}

export interface ActivatedAbility {
  type: 'activated';
  cost: AbilityCost;
  /** R49: a printed "{Battle}" / "{Deployment}" marker ON THE ABILITY (Grox,
   * Cadaverous Cultivator). doActivateAbility gates by PHASE, so without this
   * a battle-only ability was activatable during deployment too. Absent = the
   * ability may be activated in either window, the standing behaviour. */
  timing?: 'battle' | 'deploy';
  label: string;
  bounded?: boolean;
  graftCause?: boolean;
  effect: EffectDef;
}

export type Ability = TriggeredAbility | ActivatedAbility;

/** A continuous ("static") modification a card projects while it is a unit in
 * play: "+X/+Y to matching units", granted attributes, or both. Evaluated live
 * inside effStats/ownAttrs (engine stat layer 3). affects() runs for units in
 * the SAME REGION as the holder (R12) — return true to include the holder
 * itself. IMPORTANT: affects/dp/dt must not call effStats (reentrancy guard
 * makes nested statics vanish); read raw fields (counters, hand sizes, card
 * data) instead. */
export interface StaticMod {
  affects: (g: E, self: Entity, target: Entity) => boolean;
  dp?: number | ((g: E, self: Entity, target: Entity) => number);
  dt?: number | ((g: E, self: Entity, target: Entity) => number);
  attrs?: Attr[];
}

/** What a cost modifier is being asked about. `purpose` separates PLAYING a
 * card from APPLYING it as a mod — applying a mod is not playing (R37, Bena's
 * ruling), so "spells cost [one] more to PLAY" must not tax an augment. */
export interface CostCtx {
  seat: Seat;
  card: CardDef;
  region: number;
  purpose: 'play' | 'mod';
}

/**
 * R59: a continuous COST modifier, radiating from a unit in play or from an
 * augment mod exactly like a StaticMod, and scoped to the holder's region
 * (R12). `delta` returns extra mana — negative to discount. The total is
 * clamped at zero: no card ever costs less than nothing.
 *
 * Like StaticMod, `delta` must not call anything that re-enters cost
 * evaluation (canPayCard / payCard / manaToPlay); read raw state instead.
 */
export interface CostMod {
  delta?: (g: E, self: Entity, ctx: CostCtx) => number;
  /**
   * R60: extra LIFE the play costs — "Cards played during battle gain
   * [Pay 2 life]" (Arbiter of Armistice). A separate channel from `delta`
   * because life and mana are not interchangeable: the mana half gates on
   * open resources, the life half on R49's canPayLife (you may pay N life
   * only while you have MORE than N), and an unpayable life tax makes the
   * card uncastable exactly as unpayable mana does.
   */
  life?: (g: E, self: Entity, ctx: CostCtx) => number;
}

export interface CardBehavior {
  /** X-cost cards only: the smallest legal X ("X can't be zero" → 1).
   * Casting requires (and X options start at) this much open mana. */
  xMin?: number;
  abilities?: Ability[];
  /** continuous stat/attr projections while this card is a unit in play OR
   * an augment mod (text-box [Augment] statics transfer with the card) */
  statics?: StaticMod[];
  /** R59: continuous COST modifiers, same radiation rules as `statics`
   * ("Spells cost [one] more to play during battle" — Tranquility) */
  costMods?: CostMod[];
  /** the card can be applied as an augment even without augmentAttrs or
   * augmentText — its [Augment] text is implemented via `statics` */
  augmentable?: boolean;
  /** R42: this card may be prophesied out of its owner's BIN as well as their
   * hand ("I can be prophesied from your bin" — Angel of Anguish). No card may
   * be prophesied from the bin unless it says so, so this defaults to false
   * and the `prophesy` action's `from: 'bin'` is refused without it. */
  prophesyFromBin?: boolean;
  /** effect of a spell / spell unit / spell token when played */
  spellEffect?: EffectDef;
  /** the [Switch]-marked effect that transfers when this card is grafted */
  graftEffect?: { bounded: boolean; effect: EffectDef };
  /** text-box [Augment] abilities that transfer when this card augments */
  augmentText?: Ability[];
  /** R38 replacement effect: rot is about to deal `amount` damage to `seat`.
   * Return true to REPLACE the damage (do whatever the card does instead —
   * Skittering Blight: "instead put that many +1/+1 counters on me"), false to
   * let it through. Called from E.rotDamage() at the start of deployment,
   * before the damage event exists. `self` is the unit the text is anchored on
   * — the card itself when it is a unit in play, or the HOST when the text
   * arrives via an augment mod (Skittering Blight prints it under [Augment];
   * same anchoring rule as StaticMod). Deliberately a one-off hook, not a
   * replacement framework: rot damage is the only replaceable event in the
   * engine (see E.replaceRotDamage). */
  replaceRotDamage?: (g: E, self: Entity, seat: Seat, amount: number) => boolean;
  /** R38 replacement effect, the second and last one: a COLUMN is about to
   * deal `amount` combat damage to `seat`. Return true to REPLACE the damage
   * (Blightsea Polyp: "[Augment] Columns deal combat damage to players as 1
   * rot" — the card gains the victim 1 rot and returns true), false to let it
   * through. Asked once PER COLUMN, which is why the reminder text's "a column
   * of a 4/4 and a 2/2 would give the opponent 1 rot" holds whatever the
   * column's power is.
   *
   * ⚠ Replacing the damage does NOT unmake it: Caleb ruled (2024-10-24) the
   * damage still counts as having been DEALT, so {Lethal} still kills through
   * it, {Thieving} still draws, and {Blessed} still gains. Only the life total
   * is spared.
   *
   * Anchored like replaceRotDamage (a mod's hook reads from its HOST), but NOT
   * restricted to one seat's cards: the printed text says "columns", plural
   * and unowned, so every holder in play is offered the replacement and the
   * card itself decides whose columns it cares about. */
  replaceCombatDamageToPlayer?: (g: E, self: Entity, seat: Seat, amount: number,
    info: { attacker: Seat; region: number }) => boolean;
  /** UI-only PURE query (playtest #5): the amount a state-derived X spell
   * (e.g. Burning Vengeance's "units that died this battle") would use if it
   * resolved RIGHT NOW for `seat`, with `region` the active battle region.
   * Never called by the engine, apply(), or any replay-affecting path — the
   * client shows it as an "X = N right now" badge on hand cards during
   * battle. null = no meaningful number right now. */
  xPreview?: (g: E, seat: Seat, region: number) => number | null;
}

export type CardDef = Printed & CardBehavior;

const REGISTRY = new Map<string, CardDef>();
const PRINTED = printedJson as Record<string, Printed>;

export function card(name: string, behavior: CardBehavior): void {
  const printed = PRINTED[name];
  if (!printed) throw new Error(`No printed data for "${name}" — add it to scripts/extract-printed.mjs POOL`);
  REGISTRY.set(name, { ...printed, ...behavior });
  ZONE_INDEX = null;   // R51: a new registration may add a zone trigger
}

/** Register a card that is not in the oracle pool (unit tokens, test cards). */
export function registerSynthetic(printed: Printed, behavior: CardBehavior): void {
  REGISTRY.set(printed.name, { ...printed, ...behavior });
  ZONE_INDEX = null;
}

/**
 * R47: a second printed NAME for one registered card. The Wraith token is the
 * only case: the token was renamed FROM "Wight" TO "Wraith", and the printed
 * data is mid-transition in the other direction — six cards already read
 * "Wraith" while `Blight's End` still carries the OLD name ("Augment a Wight
 * onto X target units"). Both must resolve to ONE card, so the current name
 * `Wraith` is canonical and the retired `Wight` is its alias.
 *
 * Aliases resolve in getCard() only; they are deliberately NOT in
 * allCardNames(), so nothing downstream (DECK_LIST, the draft pool, the card
 * browser) can ever see the two names as two things. State always stores the
 * canonical name — the alias exists for lookups, never for storage.
 */
const ALIASES = new Map<string, string>();
export function registerAlias(alias: string, target: string): void {
  ALIASES.set(alias, target);
}
/** the registered name `name` refers to (itself, unless it is an alias) */
export function canonicalCardName(name: string): string {
  return ALIASES.get(name) ?? name;
}

export function getCard(name: string): CardDef {
  const def = REGISTRY.get(name) ?? REGISTRY.get(canonicalCardName(name));
  if (!def) throw new Error(`Unknown card "${name}"`);
  return def;
}

export function allCardNames(): string[] {
  return [...REGISTRY.keys()];
}

/** Look up the EffectDef a serialized effect key refers to. */
export function effectByKey(key: string): EffectDef {
  const [tag, rest] = [key.slice(0, key.indexOf(':')), key.slice(key.indexOf(':') + 1)];
  if (tag === 'spell') {
    const def = getCard(rest).spellEffect;
    if (!def) throw new Error(`${rest} has no spell effect`);
    return def;
  }
  const [name, idxStr] = rest.split('#');
  const idx = Number(idxStr);
  if (tag === 'ability') {
    const ab = getCard(name!).abilities?.[idx];
    if (!ab) throw new Error(`${name} has no ability #${idx}`);
    return ab.effect;
  }
  if (tag === 'graft') {
    const def = getCard(rest).graftEffect;
    if (!def) throw new Error(`${rest} has no graft effect`);
    return def.effect;
  }
  if (tag === 'augment') {
    const ab = getCard(name!).augmentText?.[idx];
    if (!ab) throw new Error(`${name} has no augment text #${idx}`);
    return ab.effect;
  }
  if (tag === 'ambush') return ambushEffect(rest);
  throw new Error(`Bad effect key "${key}"`);
}

/** The Ambush play mode's effect, shared by every ambush card (Manual p.40):
 * "Recall target ally, put me into their position in play." Target gone at
 * resolution → the item fizzles and the ambusher is binned (card ruling). */
const AMBUSH_EFFECTS = new Map<string, EffectDef>();
export function ambushEffect(name: CardName): EffectDef {
  let def = AMBUSH_EFFECTS.get(name);
  if (!def) {
    def = {
      targets: { what: 'allyUnit', prompt: `${name}: recall target ally — the ambusher takes their position` },
      run: (g, ctx) => {
        const t = ctx.targets[0];
        if (t && 'id' in (t as object)) g.ambushSwap(t as Entity, name, ctx.controller);
      },
    };
    AMBUSH_EFFECTS.set(name, def);
  }
  return def;
}

/** affinity pips of a cost string, e.g. "rr" -> { fire: 2 } */
export const ELEMENT_OF_PIP: Record<string, string> = {
  r: 'fire', b: 'water', e: 'earth', g: 'wood', m: 'metal', l: 'light', d: 'dark',
};
export function affinityPips(cost: string): Record<string, number> {
  const pips: Record<string, number> = {};
  for (const ch of cost) {
    const el = ELEMENT_OF_PIP[ch];
    if (el) pips[el] = (pips[el] ?? 0) + 1;
  }
  return pips;
}

/**
 * R51: index of the zone-resident triggers in the pool, keyed by event type.
 * fireEvent() consults it on EVERY event, so it must be a map lookup and not
 * a scan: built once, lazily (the registry fills as the batch modules import),
 * and invalidated by card()/registerSynthetic() so a late registration is
 * still seen. An event type nobody listens for costs one failed Map.get().
 */
export interface ZoneTrigger { card: string; abilityIndex: number; zone: 'bin' | 'cache' }
let ZONE_INDEX: Map<EventType, ZoneTrigger[]> | null = null;
function buildZoneIndex(): Map<EventType, ZoneTrigger[]> {
  const idx = new Map<EventType, ZoneTrigger[]>();
  for (const [name, def] of REGISTRY) {
    (def.abilities ?? []).forEach((ab, abilityIndex) => {
      if (ab.type !== 'triggered' || !ab.zone) return;
      for (const type of ab.events) {
        const list = idx.get(type) ?? [];
        list.push({ card: name, abilityIndex, zone: ab.zone });
        idx.set(type, list);
      }
    });
  }
  return idx;
}
export function zoneTriggersFor(type: EventType): ZoneTrigger[] {
  ZONE_INDEX ??= buildZoneIndex();
  return ZONE_INDEX.get(type) ?? [];
}

export function isTriggered(a: Ability): a is TriggeredAbility { return a.type === 'triggered'; }
export function isActivated(a: Ability): a is ActivatedAbility { return a.type === 'activated'; }

/** A card can be grafted onto a host iff it has a [Switch]-marked effect. */
export function isGraftable(name: string): boolean {
  return !!getCard(name).graftEffect;
}

/** A host can receive grafts iff it has its own graft cause (Manual p.33). */
export function graftCauseIndex(name: string): number {
  const abilities = getCard(name).abilities ?? [];
  return abilities.findIndex(a => a.graftCause);
}

/** A card can augment iff it grants type-line attrs or has [Augment] text. */
export function isAugment(name: string): boolean {
  const def = getCard(name);
  return def.augmentAttrs.length > 0 || (def.augmentText?.length ?? 0) > 0 || !!def.augmentable;
}
