/* Card definition DSL (docs/04 §5): declarative defs over effect primitives.
 *
 * Printed data comes from printed.json (generated by scripts/extract-printed.mjs
 * from AlgomancyCards-OracleText.json — never hand-copied). Only behavior is
 * authored here.
 *
 * Effects are code, but stack items must be serializable state — so a stack
 * item references its effects by string keys resolved through the registry:
 *   spell:<Card>       the card's spell effect
 *   ability:<Card>#<i> the effect of abilities[i]
 *   graft:<Card>       the card's [Switch]-marked transferable effect
 *   augment:<Card>#<i> the effect of augmentText[i] (text-box [Augment] text)
 */
import type {
  Attr, CardName, EngineEvent, Entity, EventType, Seat, TargetRef,
} from '../types.ts';
import type { E } from '../engine.ts';
import printedJson from './printed.json' with { type: 'json' };

export interface Printed {
  name: string;
  cost: string;                     // affinity pips, e.g. "rr"
  mana: number | 'X';
  power: number;
  toughness: number;
  type: string;
  kind: 'unit' | 'spell' | 'spellUnit' | 'spellToken';
  timing: 'deploy' | 'battle' | 'haste';
  attrs: Attr[];
  virus: boolean;
  burst: boolean;
  augmentAttrs: Attr[];             // type-line [Augment] grants (mods.py rule)
  /** "[Battle] Ambush [4bb]" alternative play mode: mana + affinity pips */
  ambush?: { cost: string; mana: number };
  text: string;
  image: string;
}

/** Resolved target passed to effect run(): an entity, a player, or a stack item id. */
export type ResolvedTarget = Entity | { player: Seat } | { stack: number };

export interface EffectCtx {
  controller: Seat;
  sourceName: string;
  sourceId?: number;
  region: number;
  targets: ResolvedTarget[];
  x?: number;
  /** R1: the event snapshot for triggered abilities (conditions were checked at
   * event time; amounts must be computed here, at resolution, from live state) */
  event: EngineEvent | null;
  /** mid-resolution choice (R4 electric path, R6 payments). Returns the stored
   * answer or suspends the engine with a decision. Parts that use this must
   * request all choices before mutating state, or use plan-then-commit —
   * the engine rolls back to the part boundary on suspension. */
  choose: (key: string, dec: { kind: 'payOrDecline' | 'electricPath'; seat: Seat; prompt: string; options: { label: string; value: unknown }[] }) => unknown;
}

export interface TargetSpec {
  what: 'unit' | 'allyUnit' | 'any' | 'stackSpell';
  prompt: string;
}

export interface EffectDef {
  targets?: TargetSpec;
  /** R5: if true, all targets invalid at resolution fizzles the whole effect.
   * Default: resolve partially against remaining legal targets. */
  allOrNothing?: boolean;
  run: (g: E, ctx: EffectCtx) => void;
}

export interface TriggeredAbility {
  type: 'triggered';
  events: EventType[];
  /** only fire when the event's source is this entity */
  self?: boolean;
  /** R1: condition — evaluated once, at event time */
  when?: (g: E, self: Entity, ev: EngineEvent) => boolean;
  label: string;
  /** [Switch1]: once per turn, tracked per card (R9) */
  bounded?: boolean;
  /** carries a graft symbol => is a graft cause (grafts can attach to it) */
  graftCause?: boolean;
  effect: EffectDef;
}

export interface ActivatedAbility {
  type: 'activated';
  cost: { mana?: number; sacrificeSelf?: boolean };
  label: string;
  bounded?: boolean;
  graftCause?: boolean;
  effect: EffectDef;
}

export type Ability = TriggeredAbility | ActivatedAbility;

/** A continuous ("static") modification a card projects while it is a unit in
 * play: "+X/+Y to matching units", granted attributes, or both. Evaluated live
 * inside effStats/ownAttrs (engine stat layer 3). affects() runs for units in
 * the SAME REGION as the holder (R12) — return true to include the holder
 * itself. IMPORTANT: affects/dp/dt must not call effStats (reentrancy guard
 * makes nested statics vanish); read raw fields (counters, hand sizes, card
 * data) instead. */
export interface StaticMod {
  affects: (g: E, self: Entity, target: Entity) => boolean;
  dp?: number | ((g: E, self: Entity, target: Entity) => number);
  dt?: number | ((g: E, self: Entity, target: Entity) => number);
  attrs?: Attr[];
}

export interface CardBehavior {
  abilities?: Ability[];
  /** continuous stat/attr projections while this card is a unit in play */
  statics?: StaticMod[];
  /** effect of a spell / spell unit / spell token when played */
  spellEffect?: EffectDef;
  /** the [Switch]-marked effect that transfers when this card is grafted */
  graftEffect?: { bounded: boolean; effect: EffectDef };
  /** text-box [Augment] abilities that transfer when this card augments */
  augmentText?: Ability[];
}

export type CardDef = Printed & CardBehavior;

const REGISTRY = new Map<string, CardDef>();
const PRINTED = printedJson as Record<string, Printed>;

export function card(name: string, behavior: CardBehavior): void {
  const printed = PRINTED[name];
  if (!printed) throw new Error(`No printed data for "${name}" — add it to scripts/extract-printed.mjs POOL`);
  REGISTRY.set(name, { ...printed, ...behavior });
}

/** Register a card that is not in the oracle pool (unit tokens, test cards). */
export function registerSynthetic(printed: Printed, behavior: CardBehavior): void {
  REGISTRY.set(printed.name, { ...printed, ...behavior });
}

export function getCard(name: string): CardDef {
  const def = REGISTRY.get(name);
  if (!def) throw new Error(`Unknown card "${name}"`);
  return def;
}

export function allCardNames(): string[] {
  return [...REGISTRY.keys()];
}

/** Look up the EffectDef a serialized effect key refers to. */
export function effectByKey(key: string): EffectDef {
  const [tag, rest] = [key.slice(0, key.indexOf(':')), key.slice(key.indexOf(':') + 1)];
  if (tag === 'spell') {
    const def = getCard(rest).spellEffect;
    if (!def) throw new Error(`${rest} has no spell effect`);
    return def;
  }
  const [name, idxStr] = rest.split('#');
  const idx = Number(idxStr);
  if (tag === 'ability') {
    const ab = getCard(name!).abilities?.[idx];
    if (!ab) throw new Error(`${name} has no ability #${idx}`);
    return ab.effect;
  }
  if (tag === 'graft') {
    const def = getCard(rest).graftEffect;
    if (!def) throw new Error(`${rest} has no graft effect`);
    return def.effect;
  }
  if (tag === 'augment') {
    const ab = getCard(name!).augmentText?.[idx];
    if (!ab) throw new Error(`${name} has no augment text #${idx}`);
    return ab.effect;
  }
  if (tag === 'ambush') return ambushEffect(rest);
  throw new Error(`Bad effect key "${key}"`);
}

/** The Ambush play mode's effect, shared by every ambush card (Manual p.40):
 * "Recall target ally, put me into their position in play." Target gone at
 * resolution → the item fizzles and the ambusher is binned (card ruling). */
const AMBUSH_EFFECTS = new Map<string, EffectDef>();
export function ambushEffect(name: CardName): EffectDef {
  let def = AMBUSH_EFFECTS.get(name);
  if (!def) {
    def = {
      targets: { what: 'allyUnit', prompt: `${name}: recall target ally — the ambusher takes their position` },
      run: (g, ctx) => {
        const t = ctx.targets[0];
        if (t && 'id' in (t as object)) g.ambushSwap(t as Entity, name, ctx.controller);
      },
    };
    AMBUSH_EFFECTS.set(name, def);
  }
  return def;
}

/** affinity pips of a cost string, e.g. "rr" -> { fire: 2 } */
export const ELEMENT_OF_PIP: Record<string, string> = {
  r: 'fire', b: 'water', e: 'earth', g: 'wood', m: 'metal',
};
export function affinityPips(cost: string): Record<string, number> {
  const pips: Record<string, number> = {};
  for (const ch of cost) {
    const el = ELEMENT_OF_PIP[ch];
    if (el) pips[el] = (pips[el] ?? 0) + 1;
  }
  return pips;
}

export function isTriggered(a: Ability): a is TriggeredAbility { return a.type === 'triggered'; }
export function isActivated(a: Ability): a is ActivatedAbility { return a.type === 'activated'; }

/** A card can be grafted onto a host iff it has a [Switch]-marked effect. */
export function isGraftable(name: string): boolean {
  return !!getCard(name).graftEffect;
}

/** A host can receive grafts iff it has its own graft cause (Manual p.33). */
export function graftCauseIndex(name: string): number {
  const abilities = getCard(name).abilities ?? [];
  return abilities.findIndex(a => a.graftCause);
}

/** A card can augment iff it grants type-line attrs or has [Augment] text. */
export function isAugment(name: string): boolean {
  const def = getCard(name);
  return def.augmentAttrs.length > 0 || (def.augmentText?.length ?? 0) > 0;
}
