export const REPO_ROOT: string;
export const DATA_DIR: string;
export const CARDS_DIR: string;
export const ORACLE_JSON: string;
/** generated by bot/pipeline/classify_complexity.py — Simple/Complex read off the scans where the oracle says Common */
export const COMPLEXITY_OVERRIDES: string;
/** generated by bot/pipeline/build_anchors.py — where each mod card's graft/augment icon sits on its scan */
export const MOD_ANCHORS: string;
export const ICONS_DIR: string;
export const RULES_DIR: string;
export const MANUAL_TXT: string;
/** the whole browser client — the game server resolves this for itself too */
export const UI_DIR: string;
/** the sound cues, one .ogg per ui/sfx.ts Cue; provenance in sfx/NOTICE.md */
export const SFX_DIR: string;
export const VAR_DIR: string;
export const ISSUES_JSONL: string;
export const VERDICTS_JSONL: string;
export const GAMES_DIR: string;
export const ISSUES_SNAPSHOT: string;
export const VERDICTS_SNAPSHOT: string;
/** BL-16: the admin's triage marks on reports — live file, then its snapshot */
export const MARKS_JSONL: string;
export const MARKS_SNAPSHOT: string;
export const DEPLOY_HOST: string;
export const DEPLOY_ROOT: string;
export function remote(abs: string): string;
