/* Where the shared, repo-level assets live — for everything that reads them
 * off the FILESYSTEM (the build scripts and the tests). The browser's own
 * copy of this question is ui/assets.ts, which deals in URLs, not paths.
 *
 * WHY THIS FILE EXISTS. Nine call sites used to spell `join(here, '..', '..',
 * '..', 'AlgomancyCards')` for themselves, in four different notations. That
 * is not just repetition: the depth is load-bearing and invisible. `engine/`
 * sits exactly three levels below the repo root, and every one of those
 * literals silently encodes that fact. Move this package one level and they
 * all resolve to somewhere that does not exist — or worse, somewhere that
 * does. Now the depth is stated once, here.
 *
 * These are the assets SHARED WITH THE PYTHON BOT (bot/paths.py names the same
 * five things). Neither side owns them; both read them. */
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));   // <repo>/client/engine/scripts

/** the repository root — three levels up from engine/ */
export const REPO_ROOT = join(HERE, '..', '..', '..');

/** the card scans, `Card-Name-With-Hyphens.jpg`, plus the oracle data */
export const DATA_DIR = join(REPO_ROOT, 'data');

/** the card scans, `Card-Name-With-Hyphens.jpg`, plus the oracle data */
export const CARDS_DIR = join(DATA_DIR, 'cards');
/** Caleb's card transcription. UPSTREAM CANONICAL — never hand-edit it;
 *  corrections belong in scripts/printed-overrides.mjs. */
export const ORACLE_JSON = join(CARDS_DIR, 'AlgomancyCards-OracleText.json');

/**
 * GENERATED by `npm run extract` from `scripts/printed-overrides.mjs`; the
 * corrections this repo carries against the canonical oracle transcription,
 * for the readers that are NOT the client.
 *
 * It exists because an override used to fix exactly one of the three
 * consumers: the Python bot and the RAG corpus read the oracle file directly
 * and went on serving a type line the owner had already ruled wrong. Read by
 * `bot/oracle.py`, named on the Python side in `bot/paths.py`.
 *
 * ⚠ Generated — never hand-edit it. Only entries whose `scope` is not
 * `'client'` are emitted; see the override table's header.
 */
export const ORACLE_CORRECTIONS = join(CARDS_DIR, 'oracle-corrections.json');
/**
 * GENERATED by `bot/pipeline/classify_complexity.py`, the other direction:
 * the Python side READS the scans and the client CONSUMES the answer. It is
 * the Simple/Complex reading of the type-bar icon on each card scan, for the
 * cards whose oracle `complexity` is the placeholder `Common` — all of Light &
 * Dark. `extract-printed.mjs` applies it into catalogue.json, refusing any
 * entry whose `from` no longer matches upstream. Named on the Python side in
 * `bot/paths.py`. ⚠ Generated — never hand-edit it.
 */
export const COMPLEXITY_OVERRIDES = join(CARDS_DIR, 'complexity-overrides.json');
/** element pips, cost circles, keyword markers */
export const ICONS_DIR = join(DATA_DIR, 'icons');
/** the rules corpus: manual, glossary, rulebook, dev-logs */
export const RULES_DIR = join(DATA_DIR, 'rules');
/** the checked-in `pdftotext -layout` extraction of the manual */
export const MANUAL_TXT = join(RULES_DIR, 'Algomancy-Manual.txt');

/* ── THE DEPLOY BOX, AND THE RUNTIME STATE THAT ONLY EXISTS THERE ─────────
 *
 * The owner's 🐛 button appends to `var/issues.jsonl` on the game server, and
 * the scenario tester appends to `var/verdicts.jsonl` beside it. Neither file
 * is in git and neither can be rebuilt, so the only way this repo ever sees
 * them is a copy fetched by hand — `npm run reports` from client/.
 *
 * WHY THEY ARE NAMED HERE. The fetch instruction used to be an scp literal
 * inside 70-playtest-ledger.test.ts, spelling `client/server/issues.jsonl`.
 * The 2026-08-30 reorg moved that file to `var/` and the literal did not move
 * with it, so the one documented repair for a stale snapshot silently fetched
 * nothing — for three rounds, while twelve owner reports (four engine-level)
 * sat unread and the ledger reported "0 live". A recovery command is only as
 * good as the path in it, so the path is stated here, once, and the remote
 * spelling is DERIVED from the local one: move `var/` and both move together.
 *
 * `server/statepaths.ts` resolves the same two files for the server itself, at
 * runtime and env-overridable. That is a second module answering the same
 * question and it cannot be collapsed — the engine must not import the server
 * — so `test/255-refresh-command.test.ts` asserts the two agree instead. */

/** every mutable thing the deployment owns; gitignored in full */
export const VAR_DIR = join(REPO_ROOT, 'var');
/** playtest reports from the in-game 🐛 button; the live file, on the server */
export const ISSUES_JSONL = join(VAR_DIR, 'issues.jsonl');
/** the scenario tester's verdicts — the owner's judgements, and the only copy */
export const VERDICTS_JSONL = join(VAR_DIR, 'verdicts.jsonl');
/** saved rooms, one JSON per room code — what replay-room.ts is pointed at */
export const GAMES_DIR = join(VAR_DIR, 'games');
/** the committed copy of ISSUES_JSONL that the ledger is checked against */
export const ISSUES_SNAPSHOT =
  join(REPO_ROOT, 'client', 'ledgers', 'playtest-issues.snapshot.jsonl');
/**
 * The committed copy of VERDICTS_JSONL, and the reason it now exists.
 *
 * Until round 36 the verdicts had no snapshot, and this file said why: "the
 * transcription in ledgers/unreached.ts is read by a human, so the raw file
 * lands in var/". That is precisely the arrangement `ISSUES_SNAPSHOT` was
 * created to replace. A `broken` verdict on Vengeance sat in var/verdicts.jsonl
 * from 2026-08-27 to 2026-09-01 — five days, through three rounds and two
 * ledger sweeps — while `card-todo.ts` reported no work outstanding, because
 * nothing offline could see the file and nothing was asserting over it.
 *
 * A queue whose only reader is a human who remembers to look is not a queue.
 */
export const VERDICTS_SNAPSHOT =
  join(REPO_ROOT, 'client', 'ledgers', 'verdicts.snapshot.jsonl');

/** the deploy box — NOT the dev laptop, and since 2026-09-05 NOT the home
 * server either: the VPS behind algomancy.online. This is the
 * ssh name (a `Host algomancy-vps` entry in ~/.ssh/config on the dev
 * machine) and the box's own hostname; fetch-reports.mjs compares the two to
 * refuse to run there. See CLAUDE.md § Deploy. */
export const DEPLOY_HOST = 'algomancy-vps';
/** this repo's checkout on the deploy box; same path, different machine */
export const DEPLOY_ROOT = '/home/bena/Documents/Algomancy';

/**
 * The same file, spelled for scp: `<host>:<path>`.
 *
 * Derived from the local constant on purpose. A hand-written remote path is a
 * copy of a fact, and copies rot silently because nothing on this machine can
 * check them — that is exactly how the issues.jsonl fetch broke.
 */
export function remote(abs) {
  return `${DEPLOY_HOST}:${DEPLOY_ROOT}/${relative(REPO_ROOT, abs).split(sep).join('/')}`;
}
