export const REPO_ROOT: string;
export const DATA_DIR: string;
export const CARDS_DIR: string;
export const ORACLE_JSON: string;
/** generated by `npm run extract` from printed-overrides.mjs; read by bot/oracle.py */
export const ORACLE_CORRECTIONS: string;
export const ICONS_DIR: string;
export const RULES_DIR: string;
export const MANUAL_TXT: string;
export const VAR_DIR: string;
export const ISSUES_JSONL: string;
export const VERDICTS_JSONL: string;
export const GAMES_DIR: string;
export const ISSUES_SNAPSHOT: string;
export const VERDICTS_SNAPSHOT: string;
export const DEPLOY_HOST: string;
export const DEPLOY_ROOT: string;
export function remote(abs: string): string;
