export const REPO_ROOT: string;
export const DATA_DIR: string;
export const CARDS_DIR: string;
export const ORACLE_JSON: string;
/** generated by bot/pipeline/classify_complexity.py — Simple/Complex read off the scans where the oracle says Common */
export const COMPLEXITY_OVERRIDES: string;
/** generated by bot/pipeline/build_anchors.py — where each mod card's graft/augment icon sits on its scan */
export const MOD_ANCHORS: string;
/** generated by bot/pipeline/read_text_boxes.py — where each scan's type bar (the rules box) starts */
export const TEXT_BOXES: string;
export const ICONS_DIR: string;
export const RULES_DIR: string;
export const RULINGS_EXPORTS: string;
export const MANUAL_TXT: string;
/** the engine's spec, client/docs/digital-rules.md — the `## R<n>` register */
export const DIGITAL_RULES: string;
/** data/comprehensive-rules/ — see its README for which files are generated */
export const CR_DIR: string;
export const CR_RULES_DIR: string;
/** committed reviewed state — append/edit only through the cr scripts */
export const CR_LEDGER: string;
export const CR_SUPERSESSION: string;
export const CR_CLASSIFICATION: string;
export const CR_VERDICTS: string;
/** generated — never hand-edit */
export const CR_DISCREPANCIES: string;
export const CR_FINDINGS: string;
export const CR_BUILD_DIR: string;
export const CR_DOC: string;
export const CR_DOC_HTML: string;
export const CR_DOC_TXT: string;
export const CR_ANNEX_D: string;
/** the whole browser client — the game server resolves this for itself too */
export const UI_DIR: string;
/** the sound cues, one .ogg per ui/sfx.ts Cue; provenance in sfx/NOTICE.md */
export const SFX_DIR: string;
export const VAR_DIR: string;
export const ISSUES_JSONL: string;
export const VERDICTS_JSONL: string;
export const GAMES_DIR: string;
export const ISSUES_SNAPSHOT: string;
export const RAQ_SNAPSHOT: string;
export const VERDICTS_SNAPSHOT: string;
/** BL-16: the admin's triage marks on reports — live file, then its snapshot */
export const MARKS_JSONL: string;
export const MARKS_SNAPSHOT: string;
export const PROD_MIRROR_DIR: string;
export const DEPLOY_HOST: string;
export const DEPLOY_ROOT: string;
export function remote(abs: string): string;
